(function(){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d));}catch(e){return d;}};
  const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const appKey='nexca_org_apps_v1', ctKey='nexca_org_contracts_v1', rvKey='nexca_core_reviews_v1';
  const plans=[{id:'flyer',name:'チラシ掲載',description:'まとめ見掲載＋詳細ページ',price:0,billing_unit:'campaign',media_type:'flyer',is_active:true},{id:'video',name:'動画掲載',description:'動画フィード＋まとめ見＋詳細ページ',price:0,billing_unit:'campaign',media_type:'video',is_active:true},{id:'video_thumb',name:'動画＋サムネ掲載',description:'動画フィード＋まとめ見＋詳細ページ',price:0,billing_unit:'campaign',media_type:'video_with_thumbnail',is_active:true},{id:'option',name:'制作オプション',description:'動画制作・キャラ制作・サムネ制作の追加余地',price:null,billing_unit:'option',media_type:'all',is_active:true}];
  function apps(){return get(appKey,[]);}
  function contracts(){return get(ctKey,[]);}
  function reviews(){return get(rvKey,[]);}
  function boot(){document.body.innerHTML=shell();renderAll();}
  function shell(){return `<div class="nxp"><div class="nxp-head"><div class="nxp-head-in"><div class="nxp-logo">NEX<span>CA</span></div><div class="nxp-badge">ADMIN</div><div class="nxp-spacer"></div><button class="nxp-btn ghost" onclick="location.href='index.html'">ユーザー画面</button><button class="nxp-btn ghost" onclick="location.href='organizer.html'">主催者画面</button></div></div><div class="nxp-shell"><div class="nxp-tabs">${['dash:ダッシュボード','apps:申請一覧','review:内容確認','orgs:主催者','codes:参加コード','reviews:参加者の声','plans:料金/プラン','contracts:契約履歴','analytics:分析'].map((x,i)=>{const [id,l]=x.split(':');return `<button class="nxp-tab ${i?'':'on'}" onclick="AdminP1.tab('${id}',this)">${l}</button>`}).join('')}</div>${['dash','apps','review','orgs','codes','reviews','plans','contracts','analytics'].map((id,i)=>`<section id="${id}" class="nxp-screen ${i?'':'on'}"></section>`).join('')}</div></div>`;}
  function tab(id,btn){document.querySelectorAll('.nxp-tab').forEach(b=>b.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.nxp-screen').forEach(s=>s.classList.remove('on'));document.getElementById(id).classList.add('on');}
  function renderAll(){renderDash();renderApps();renderReview();renderOrgs();renderCodes();renderReviews();renderPlans();renderContracts();renderAnalytics();}
  function counts(){const a=apps();return {pending:a.filter(x=>x.status==='申請中').length,returned:a.filter(x=>x.status==='差し戻し').length,published:a.filter(x=>x.status==='公開中').length,ended:a.filter(x=>x.status==='掲載終了').length,orgs:new Set(a.map(x=>x.organizer_id)).size||1,likes:a.reduce((n,x)=>n+(x.likes||24),0),links:a.reduce((n,x)=>n+(x.linkClicks||18),0),codes:a.reduce((n,x)=>n+(x.codeUses||5),0)};}
  function renderDash(){const c=counts();document.getElementById('dash').innerHTML=`<div class="nxp-kpis">${[['申請中',c.pending],['差し戻し',c.returned],['公開中',c.published],['掲載終了',c.ended],['主催者数',c.orgs],['今日のいいね',c.likes],['リンククリック',c.links],['参加コード使用',c.codes]].map(x=>`<div class="nxp-kpi"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div><div class="nxp-card"><div class="nxp-title">運営ワークフロー</div><p class="nxp-sub">申請内容確認、編集、主催者確認待ち、差し戻し、承認、即公開/公開予約、参加コード発行、レビュー管理までを分離しています。</p></div>`;}
  function renderApps(){const a=apps();document.getElementById('apps').innerHTML=`<table class="nxp-table"><thead><tr><th>タイトル</th><th>主催者</th><th>ジャンル</th><th>タイプ</th><th>ステータス</th><th>申請日</th><th>操作</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.organizer_id)}</td><td>${esc(x.category)}</td><td>${esc(x.media_type)}</td><td>${esc(x.status)}</td><td>${esc((x.submitted_at||'').slice(0,10))}</td><td><button class="nxp-btn ghost" onclick="AdminP1.openReview('${x.id}')">確認</button></td></tr>`).join('')||'<tr><td colspan="7">申請はまだありません</td></tr>'}</tbody></table>`;}
  function renderReview(id){const a=apps(), x=id?a.find(v=>v.id===id):a[0];document.getElementById('review').innerHTML=x?`<div class="nxp-card"><div class="nxp-title">掲載内容確認/編集</div><div class="nxp-form"><label>タイトル</label><input class="nxp-input" id="ad-title" value="${esc(x.title)}"><label>キャッチコピー</label><input class="nxp-input" id="ad-catch" value="${esc(x.catchcopy)}"><label>説明文</label><textarea class="nxp-textarea" id="ad-desc">${esc(x.description)}</textarea><label>詳細情報</label><textarea class="nxp-textarea" id="ad-detail">${esc(x.detail_info)}</textarea><label>ユニーク情報</label><textarea class="nxp-textarea" id="ad-unique">${esc(x.unique_info)}</textarea><div class="nxp-split"><div><label>ステータス</label><select class="nxp-select" id="ad-status">${['主催者確認待ち','差し戻し','承認済み','公開予約','公開中','掲載終了','非公開'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div><label>参加コード</label><input class="nxp-input" id="ad-code" value="${esc(x.participation_code||'')}"></div></div><label>運営コメント / 差し戻し理由</label><textarea class="nxp-textarea" id="ad-comment">${esc(x.admin_comment||'')}</textarea><div class="nxp-actions"><button class="nxp-btn green" onclick="AdminP1.saveReview('${x.id}')">保存</button><button class="nxp-btn yellow" onclick="AdminP1.publish('${x.id}')">承認して公開</button><button class="nxp-btn ghost" onclick="AdminP1.returnApp('${x.id}')">差し戻し</button></div></div></div>`:'<div class="nxp-card"><p class="nxp-muted">確認対象がありません。</p></div>';}
  function openReview(id){tab('review',document.querySelectorAll('.nxp-tab')[2]);renderReview(id);}
  function saveReview(id){set(appKey,apps().map(x=>x.id===id?{...x,title:document.getElementById('ad-title').value,catchcopy:document.getElementById('ad-catch').value,description:document.getElementById('ad-desc').value,detail_info:document.getElementById('ad-detail').value,unique_info:document.getElementById('ad-unique').value,status:document.getElementById('ad-status').value,participation_code:document.getElementById('ad-code').value,admin_comment:document.getElementById('ad-comment').value,updated_at:new Date().toISOString()}:x));renderAll();}
  function publish(id){set(appKey,apps().map(x=>x.id===id?{...x,status:'公開中',publish_at:new Date().toISOString(),show_in_video_feed:x.media_type!=='flyer',show_in_flyer_view:true}:x));renderAll();}
  function returnApp(id){set(appKey,apps().map(x=>x.id===id?{...x,status:'差し戻し',admin_comment:document.getElementById('ad-comment')?.value||'内容を確認してください'}:x));renderAll();}
  function renderOrgs(){const orgs=[...new Set(apps().map(x=>x.organizer_id||'local-organizer'))];document.getElementById('orgs').innerHTML=`<div class="nxp-list">${orgs.map(o=>`<div class="nxp-row"><h3>${esc(o)}</h3><p>掲載数 ${apps().filter(x=>x.organizer_id===o).length} / 初期掲載パートナー / Nexca確認予定</p><div class="nxp-pills"><span class="nxp-pill green">Nexca確認済み</span><span class="nxp-pill yellow">初期掲載パートナー</span></div></div>`).join('')||'<div class="nxp-card">主催者はまだありません</div>'}</div>`;}
  function renderCodes(){const rows=apps().filter(x=>x.participation_code);document.getElementById('codes').innerHTML=`<div class="nxp-list">${rows.map(x=>`<div class="nxp-row"><h3>${esc(x.title)}</h3><p>code: ${esc(x.participation_code)} / listing_id: ${esc(x.id)} / organizer_id: ${esc(x.organizer_id)}</p><div class="nxp-pills"><span class="nxp-pill green">有効</span><span class="nxp-pill">${x.codeUses||0} 使用</span></div></div>`).join('')||'<div class="nxp-card">参加コードはまだありません</div>'}</div>`;}
  function renderReviews(){const r=reviews();document.getElementById('reviews').innerHTML=`<div class="nxp-list">${r.map(x=>`<div class="nxp-row"><h3>${'★'.repeat(x.rating)} ${esc(x.displayName)}</h3><p>${esc(x.comment)}</p><div class="nxp-actions"><button class="nxp-btn green" onclick="AdminP1.modReview('${x.id}','approved')">承認</button><button class="nxp-btn ghost" onclick="AdminP1.modReview('${x.id}','rejected')">非表示</button></div></div>`).join('')||'<div class="nxp-card">参加者の声はまだありません</div>'}</div>`;}
  function modReview(id,status){set(rvKey,reviews().map(x=>x.id===id?{...x,moderationStatus:status,moderation_status:status}:x));renderAll();}
  function renderPlans(){document.getElementById('plans').innerHTML=`<div class="nxp-grid">${plans.map(p=>`<div class="nxp-card"><div class="nxp-title">${esc(p.name)}</div><p class="nxp-sub">${esc(p.description)}</p><div class="nxp-pills"><span class="nxp-pill green">12月31日まで無料</span><span class="nxp-pill yellow">初期100社 30%OFF永久</span></div></div>`).join('')}</div>`;}
  function renderContracts(){const c=contracts();document.getElementById('contracts').innerHTML=`<table class="nxp-table"><thead><tr><th>主催者</th><th>バージョン</th><th>署名者</th><th>店舗/会社</th><th>同意日時</th><th>確認</th></tr></thead><tbody>${c.map(x=>`<tr><td>${esc(x.organizer_id)}</td><td>${esc(x.contract_version)}</td><td>${esc(x.signer_name)}</td><td>${esc(x.company_or_store_name)}</td><td>${esc(x.signed_at)}</td><td>全文/素材/正確性/SNS/アンケート</td></tr>`).join('')||'<tr><td colspan="6">契約同意履歴はまだありません</td></tr>'}</tbody></table>`;}
  function renderAnalytics(){const c=counts();document.getElementById('analytics').innerHTML=`<div class="nxp-kpis"><div class="nxp-kpi"><b>${c.likes}</b><span>いいね</span></div><div class="nxp-kpi"><b>${c.links}</b><span>リンククリック</span></div><div class="nxp-kpi"><b>${c.codes}</b><span>参加コード使用</span></div><div class="nxp-kpi"><b>${apps().length}</b><span>掲載総数</span></div></div><div class="nxp-card"><div class="nxp-title">有料分析の土台</div><p class="nxp-sub">年齢層、地域、タグ、日別クリック、いいね推移を link_clicks / likes / participation_code_redemptions / reviews に分けて集計する設計です。</p></div>`;}
  window.AdminP1={tab,openReview,saveReview,publish,returnApp,modReview};
  document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,80));
})();
