(function(){
  'use strict';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const today=new Date('2026-05-11T12:00:00+09:00');
  const store={
    profile:'nexca_core_profile_v1',likes:'nexca_core_likes_v1',redemptions:'nexca_core_redemptions_v1',
    reviews:'nexca_core_reviews_v1',clicks:'nexca_core_clicks_v1'
  };
  const areas=['広島県全域','広島市中区','広島市東区','広島市南区','広島市西区','広島市安佐南区','広島市安佐北区','広島市安芸区','広島市佐伯区','呉市','福山市','東広島市','廿日市市','尾道市','三原市','その他・県外'];
  const tags=['友達と','デート向け','1人でもOK','グループ向け','家族向け','無料','予約不要','雨の日OK','夜OK','学生向け','初心者OK','当日参加OK','写真映え','穴場','癒し','交流できる','作れる','学べる','限定感','非日常','古着好き向け','カフェ巡り','ものづくり','ライブ/音楽','マーケット','ワークショップ'];
  const organizers=[
    {id:'org-vintage-loop',name:'Loop Yard Hiroshima',description:'広島の若者がふらっと立ち寄れる古着ショップ。初心者でも選びやすいラック構成を大切にしています。',icon:'👕',cover:['#315f4c','#76b06f'],genres:['古着'],area:'広島市中区',address:'広島市中区袋町周辺',instagramUrl:'https://instagram.com/',websiteUrl:'https://example.com/',phoneNumber:'082-000-0001',showPhone:true,trustLabels:['Nexca確認済み','初期掲載パートナー','参加コード対応'],isInitialPartner:true,isVerified:true,totalLikes:0,totalLinkClicks:0},
    {id:'org-soft-cafe',name:'Soft Hour Cafe',description:'会話しやすさと写真映えを両立したカフェ運営者。学生の放課後利用を想定しています。',icon:'☕',cover:['#7a4b2a','#d99a57'],genres:['カフェ'],area:'広島市西区',address:'広島市西区横川周辺',instagramUrl:'https://instagram.com/',websiteUrl:'https://example.com/',phoneNumber:'082-000-0002',showPhone:false,trustLabels:['Nexca確認済み','参加コード対応'],isInitialPartner:true,isVerified:true,totalLikes:0,totalLinkClicks:0},
    {id:'org-popup-lab',name:'Hiroshima Pop Lab',description:'マーケット、ものづくり、音楽体験を組み合わせる主催者。初参加でも入りやすいイベント設計を重視。',icon:'🎪',cover:['#9d334a','#ef8b52'],genres:['イベント・体験'],area:'広島市南区',address:'広島市南区宇品周辺',instagramUrl:'https://instagram.com/',websiteUrl:'https://example.com/',phoneNumber:'082-000-0003',showPhone:true,trustLabels:['Nexca確認済み','初期掲載パートナー'],isInitialPartner:true,isVerified:true,totalLikes:0,totalLinkClicks:0}
  ];
  const listings=[
    item('v1','video','古着','Loop Yard 週末ラック','最初の一着が見つかる、やさしい古着ラック。','org-vintage-loop','広島市中区','¥1,000〜','evergreen','','','12:00-20:00',['古着好き向け','初心者OK','友達と'],'VINTAGE50','#315f4c','#8dd07c','👕',34.392,132.456),
    item('v2','video_with_thumbnail','古着','夜のリメイク相談室','眠っている服を、もう一度好きになる。','org-vintage-loop','広島市中区','相談無料','fixed_date','2026-05-24','2026-05-24','18:00-21:00',['夜OK','作れる','学生向け'],'REMAKE24','#3f315f','#9d75e8','🧵',34.393,132.459),
    item('v3','flyer','古着','古着はじめて市','学生向けの低価格ラックをまとめて見比べ。','org-vintage-loop','広島市西区','¥500〜','date_range','2026-05-18','2026-05-31','11:00-18:00',['マーケット','無料','古着好き向け'],'MARKET31','#5a4b28','#e0b84f','🛍️',34.402,132.438),
    item('c1','video','カフェ','Soft Hour 放課後ラテ','話したい日も、ひとりの日も、ちょうどいい一杯。','org-soft-cafe','広島市西区','¥450〜','evergreen','','','10:00-21:00',['カフェ巡り','1人でもOK','癒し'],'CAFE50','#74411f','#df9a54','☕',34.398,132.442),
    item('c2','video_with_thumbnail','カフェ','雨の日クリームソーダ','雨の日だけの静かな窓際席。','org-soft-cafe','広島市中区','¥680','date_range','2026-05-11','2026-06-10','13:00-19:00',['雨の日OK','写真映え','デート向け'],'RAIN68','#315c78','#75c8e8','🍹',34.389,132.455),
    item('c3','flyer','カフェ','朝の読書モーニング','スマホを置いて、30分だけ整える朝。','org-soft-cafe','廿日市市','¥700','evergreen','','','08:00-11:00',['1人でもOK','癒し','予約不要'],'MORNING7','#6c5729','#e6c16d','📚',34.349,132.331),
    item('e1','video','イベント・体験','港のミニ音楽会','夕方の港で、知らない音に出会う。','org-popup-lab','広島市南区','無料','fixed_date','2026-05-17','2026-05-17','17:00-19:00',['無料','ライブ/音楽','友達と'],'EVENT100','#9d334a','#ef8b52','🎤',34.360,132.468),
    item('e2','video_with_thumbnail','イベント・体験','はじめての陶芸ワークショップ','不器用でも、自分の器ができる。','org-popup-lab','東広島市','¥1,800','date_range','2026-05-18','2026-05-26','10:00-16:00',['ワークショップ','作れる','初心者OK'],'CLAY18','#734f32','#d0915a','🏺',34.426,132.743),
    item('e3','flyer','イベント・体験','夜市ポップアップ','屋台、古着、音楽。週末だけの小さな非日常。','org-popup-lab','尾道市','入場無料','fixed_date','2026-05-31','2026-05-31','16:00-21:00',['非日常','マーケット','当日参加OK'],'NIGHT31','#2f416b','#7aa6ef','🏮',34.409,133.205),
    item('e4','video','イベント・体験','春のものづくり体験アーカイブ','終了した投稿は、主催者ページの過去投稿に残る。','org-popup-lab','広島市南区','¥1,000','fixed_date','2026-05-03','2026-05-03','13:00-16:00',['ものづくり','作れる','初心者OK'],'ARCHIVE03','#4b3b76','#9d7be8','🧶',34.364,132.465)
  ];
  window.NEXCA_CORE_TABLES={
    users:['id','nickname','age_group','area','created_at','updated_at'],
    listings:['id','title','catchcopy','description','detailInfo','uniqueInfo','category','mediaType','mediaUrl','thumbnailUrl','flyerImageUrl','showInVideoFeed','showInFlyerView','organizerId','tags','area','address','latitude','longitude','priceText','targetAgeGroups','eventDateType','startDate','endDate','businessHours','reservationUrl','instagramUrl','websiteUrl','phoneNumber','showPhone','status','isArchived','createdAt','updatedAt'],
    organizers:['id','name','description','iconUrl','coverUrl','genres','area','address','instagramUrl','websiteUrl','phoneNumber','showPhone','trustLabels','isInitialPartner','isVerified','totalLikes','totalLinkClicks'],
    likes:['user_id','listing_id','created_at','age_group','area'],
    participation_codes:['id','code','listing_id','organizer_id','genre','reward_points','is_active','valid_from','valid_until','max_uses_per_user'],
    participation_code_redemptions:['user_id','code','listing_id','organizer_id','genre','redeemed_at','points'],
    reviews:['id','user_id','listing_id','rating','comment','display_name_type','moderationStatus','created_at'],
    link_clicks:['listing_id','organizer_id','link_type','clicked_at','user_id','age_group','area'],
    media_assets:['id','listing_id','type','url','thumbnail_url','status']
  };
  function item(id,mediaType,category,title,catchcopy,organizerId,area,priceText,eventDateType,startDate,endDate,businessHours,tags,code,c1,c2,icon,latitude,longitude){
    return {id,title,catchcopy,description:catchcopy+' 初めてでも判断しやすいよう、雰囲気・料金・場所・楽しみ方をNexcaで整理しています。',detailInfo:'所要時間、混雑しやすい時間、初めての人向けの楽しみ方まで、ユーザーが迷わず判断できる情報をまとめています。',uniqueInfo:'ショート動画、まとめ見、参加コード、参加者の声が一つの導線でつながる掲載です。',category,mediaType,mediaUrl:mediaType==='flyer'?'':'sample-video',thumbnailUrl:'',flyerImageUrl:'',showInVideoFeed:mediaType!=='flyer',showInFlyerView:true,organizerId,tags,area,address:area+' 周辺',latitude,longitude,priceText,targetAgeGroups:['中学生','高校生','大学生','社会人'],eventDateType,startDate,endDate,businessHours,reservationUrl:'https://example.com/reserve',instagramUrl:'https://instagram.com/',websiteUrl:'https://example.com/',phoneNumber:'082-000-0000',showPhone:id==='v1'||id==='e1',status:'published',isArchived:false,createdAt:'2026-05-01',updatedAt:'2026-05-11',code,colors:[c1,c2],icon,mediaLabel:mediaType==='flyer'?'チラシ':mediaType==='video_with_thumbnail'?'動画＋サムネ':'動画あり',reviews:[{rating:5,displayName:'高校生ユーザー',comment:'雰囲気が分かりやすくて、初めてでも行きやすかった。',moderationStatus:'approved'}]};
  }
  const state={genre:'all',date:'all',area:'all',tag:'all',query:'',near:false,coords:null};
  function ls(key,def){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(def));}catch(e){return def;}}
  function setls(key,val){localStorage.setItem(key,JSON.stringify(val));}
  function profile(){return ls(store.profile,{nickname:'ゲスト',age:localStorage.getItem('nx_age')||'高校生',area:'広島市中区'});}
  function likes(){return new Set(ls(store.likes,[]));}
  function redemptions(){return ls(store.redemptions,[]);}
  function reviews(){return ls(store.reviews,[]);}
  function allReviews(id){return listings.find(x=>x.id===id).reviews.concat(reviews().filter(r=>r.listingId===id&&r.moderationStatus!=='rejected'));}
  function activeListing(x){return !x.isArchived && (!x.endDate || new Date(x.endDate+'T23:59:59+09:00')>=today);}
  function filtered(base){
    let arr=base.filter(x=>state.genre==='all'||x.category===state.genre).filter(x=>state.area==='all'||x.area===state.area||state.area==='現在地周辺').filter(x=>state.tag==='all'||x.tags.includes(state.tag));
    if(state.query) arr=arr.filter(x=>(x.title+x.catchcopy+x.area+x.tags.join('')).includes(state.query));
    if(state.date!=='all') arr=arr.filter(matchDate);
    if(state.near && state.coords) arr=arr.slice().sort((a,b)=>dist(a)-dist(b));
    return arr;
  }
  function matchDate(x){
    if(x.eventDateType==='evergreen') return ['all','month'].includes(state.date);
    const s=new Date((x.startDate||x.endDate)+'T00:00:00+09:00'), e=new Date((x.endDate||x.startDate)+'T23:59:59+09:00');
    const day=today.getDay(), weekendStart=new Date(today); weekendStart.setDate(today.getDate()+(6-day+7)%7); const weekendEnd=new Date(weekendStart); weekendEnd.setDate(weekendStart.getDate()+1);
    if(state.date==='today') return s<=today&&e>=today;
    if(state.date==='tomorrow'){const t=new Date(today);t.setDate(t.getDate()+1);return s<=t&&e>=t;}
    if(state.date==='week'){const t=new Date(today);t.setDate(t.getDate()+7);return e>=today&&s<=t;}
    if(state.date==='weekend') return e>=weekendStart&&s<=weekendEnd;
    if(state.date==='month') return e>=today&&s.getMonth()===today.getMonth();
    return true;
  }
  function dist(x){if(!state.coords)return 999999;const R=6371,dLat=(x.latitude-state.coords.lat)*Math.PI/180,dLon=(x.longitude-state.coords.lng)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(state.coords.lat*Math.PI/180)*Math.cos(x.latitude*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
  function ensureSetup(){
    if($('#core-setup')) return;
    document.body.insertAdjacentHTML('beforeend',`<div id="core-setup"><div class="core-setup-box"><h2>Nexcaの初期設定</h2><p>おすすめ表示と地域別の反応分析に使う、最小限のプロフィールです。マイページからいつでも変更できます。</p><label>ニックネーム</label><input id="core-nick" placeholder="例：たいち"><label>年齢層</label><select id="core-age">${['中学生','高校生','大学生','社会人'].map(x=>`<option>${x}</option>`).join('')}</select><label>地域</label><select id="core-area">${areas.map(x=>`<option>${x}</option>`).join('')}</select><button onclick="NexcaCore.saveProfile()">Nexcaをはじめる</button></div></div>`);
  }
  function maybeShowSetup(){ensureSetup();if(!localStorage.getItem(store.profile)){$('#core-setup').classList.add('on');}}
  function saveProfile(){const p={nickname:$('#core-nick').value.trim()||'Nexcaユーザー',age:$('#core-age').value,area:$('#core-area').value};setls(store.profile,p);localStorage.setItem('nx_age',p.age);try{age=p.age;city=p.area;}catch(e){}$('#core-setup').classList.remove('on');toast('プロフィールを設定しました');renderMP();}
  function setupNav(){const labs=$$('#nav .nb-lb');if(labs[1])labs[1].textContent='まとめ見';const title=$('.fl-title');if(title){title.textContent='まとめ見';title.classList.add('core-title');}}
  function filtersHtml(target){const current=state.genre==='all'?'ジャンル':state.genre;return `<div class="${target==='feed'?'core-filter':'core-list-filter'}"><button class="core-chip ${state.genre!=='all'?'on':''}" onclick="NexcaCore.openFilterSheet()">${current}</button><button class="core-chip ${state.date==='today'?'on':''}" onclick="NexcaCore.setFilter('date','today')">今日</button><button class="core-chip ${state.date==='weekend'?'on':''}" onclick="NexcaCore.setFilter('date','weekend')">週末</button><button class="core-chip ${state.area==='現在地周辺'?'on':''}" onclick="NexcaCore.useLocation()">近く</button><button class="core-chip" onclick="NexcaCore.openFilterSheet()">フィルター</button></div>`;}
  function setFilter(k,v){state[k]=state[k]===v?'all':v;renderFeed();renderFlyer();}
  function renderFeed(){
    const root=$('#feed'); if(!root) return;
    let f=$('#core-feed-filter'); if(!f){$('#fhd').insertAdjacentHTML('afterend','<div id="core-feed-filter"></div>');f=$('#core-feed-filter');}
    f.innerHTML=filtersHtml('feed');
    const arr=filtered(listings.filter(x=>x.showInVideoFeed&&activeListing(x)));
    const st=$('#stack'); if(!st) return;
    if(!arr.length){st.innerHTML='<div class="empty" style="position:absolute;inset:0;display:flex;"><div class="empty-ic">🔍</div><div class="empty-t">条件に合う動画掲載がありません</div></div>';return;}
    st.innerHTML=arr.map((x,i)=>slideHtml(x,i)).join('');
    if(typeof fevs!=='undefined'){try{fevs=arr;idx=0;}catch(e){}}
    try{updPos();}catch(e){$$('.slide').forEach((s,i)=>s.className='slide '+(i?'dn':'cur'));}
  }
  function slideHtml(x,i){const like=likes().has(x.id), org=organizers.find(o=>o.id===x.organizerId), map='https://maps.google.com/?q='+encodeURIComponent(x.address);return `<div class="slide ${i?'dn':'cur'}" data-i="${i}"><div class="core-feed-card"><div class="core-media" style="--c1:${x.colors[0]};--c2:${x.colors[1]};"><div class="core-reel"><div class="core-reel-label">${esc(x.mediaLabel)} / 15-30 sec</div><div class="core-reel-icon">${x.icon}</div><div class="core-reel-title">${esc(x.catchcopy)}</div></div></div><div class="srt core-actions"><button class="sact ${like?'lk':''}" id="lb-${x.id}" onclick="toggleLike('${x.id}')"><div class="sact-c">${like?'❤️':'🤍'}</div><div class="sact-l">気になる</div><div class="core-action-count">${likeCount(x)}</div></button><button class="sact" onclick="shareEv('${x.id}')"><div class="sact-c">📤</div><div class="sact-l">共有</div></button><button class="sact" onclick="NexcaCore.openOrganizer('${x.organizerId}')"><div class="sact-c">店</div><div class="sact-l">主催者</div></button><a class="sact" href="${map}" target="_blank" onclick="NexcaCore.trackLink('${x.id}','map')"><div class="sact-c">📍</div><div class="sact-l">地図</div></a></div><div class="core-feed-bottom"><div class="sgtag">${esc(x.category)} · ${esc(x.area)}</div><div class="stitle">${esc(x.title)}</div><div class="core-catch">${esc(x.catchcopy)}</div><div class="core-tags">${x.tags.slice(0,3).map(t=>`<span class="core-tag">${esc(t)}</span>`).join('')}</div><button class="sdbtn" onclick="openDrw('${x.id}')">詳細を見る</button><button class="core-host-link" onclick="NexcaCore.openOrganizer('${x.organizerId}')">${esc(org?.name||'主催者')}</button></div></div></div>`;}
  function likeCount(x){return 12+likes().has(x.id)+x.id.charCodeAt(1)%16;}
  function renderFlyerTabs(){const w=$('#ftabs-wrap');if(w)w.innerHTML=filtersHtml('list');}
  function renderFlyer(){
    const grid=$('#flgrid'); if(!grid)return;
    const flscr=$('#flscr'); if(flscr&&!$('#core-list-tools'))flscr.insertAdjacentHTML('afterbegin',`<div id="core-list-tools" class="core-list-tools"><input class="core-search" placeholder="タイトル・エリア・タグで検索" oninput="NexcaCore.search(this.value)"><div id="core-near"></div></div>`);
    const near=$('#core-near'); if(near)near.innerHTML=`<div class="core-near"><b>近くのNexca</b><span>${state.coords?'現在地から近い順に並べ替え中。':'位置情報を許可すると、現在地から近い順で見られます。許可しない場合は登録地域を基準に表示します。'}</span><button onclick="NexcaCore.useLocation()">現在地周辺を見る</button></div>`;
    const arr=filtered(listings.filter(x=>x.showInFlyerView));
    grid.className='core-grid';
    grid.innerHTML=arr.map(cardHtml).join('')||'<div class="empty">掲載がありません</div>';
    const mp=$('#mplist'); if(mp)mp.innerHTML=arr.map(x=>`<a class="mpitem" href="https://maps.google.com/?q=${encodeURIComponent(x.address)}" target="_blank">${x.icon} ${esc(x.title)}</a>`).join('');
  }
  function cardHtml(x){const labels=[x.mediaLabel,statusLabel(x),x.eventDateType==='evergreen'?'通年':'受付中'];return `<div class="core-card" onclick="openDrw('${x.id}')"><div class="core-thumb" style="--c1:${x.colors[0]};--c2:${x.colors[1]};"><div class="core-badges">${labels.map(l=>`<span class="core-badge">${esc(l)}</span>`).join('')}</div><span>${x.icon}</span></div><div class="core-card-body"><h3>${esc(x.title)}</h3><p>${esc(x.catchcopy)}</p><div class="core-meta"><span>${esc(x.category)}</span><span>${esc(x.area)}</span><span>${esc(x.priceText)}</span></div></div></div>`;}
  function statusLabel(x){if(x.endDate){const left=Math.ceil((new Date(x.endDate+'T23:59:59+09:00')-today)/86400000);if(left>=0&&left<=7)return '終了間近';}return x.eventDateType==='evergreen'?'通年':'開催中';}
  function openDrw(id){const x=listings.find(l=>l.id===id);if(!x)return;const org=organizers.find(o=>o.id===x.organizerId), map='https://maps.google.com/?q='+encodeURIComponent(x.address);trackLink(x.id,'detail_open');$('#drwbody').innerHTML=`<button class="bkbtn" onclick="closeDrw()">← 戻る</button><div class="core-detail-media" style="--c1:${x.colors[0]};--c2:${x.colors[1]};"><div class="core-reel-icon">${x.icon}</div></div><div class="drw-t">${esc(x.title)}</div><div class="core-catch">${esc(x.catchcopy)}</div><div class="core-tags">${x.tags.slice(0,3).map(t=>`<span class="core-tag">${esc(t)}</span>`).join('')}</div><div class="core-info-grid">${info('ジャンル',x.category)}${info('開催/営業時間',dateText(x))}${info('料金',x.priceText)}${info('対象年齢',x.targetAgeGroups.join('・'))}${info('場所',x.area)}${info('住所',x.address)}</div><div class="core-links"><a class="core-link-btn primary" href="${x.reservationUrl}" target="_blank" onclick="NexcaCore.trackLink('${x.id}','reservation')">外部サイトで予約/申込</a><button class="core-link-btn" onclick="NexcaCore.interest('${x.id}')">Nexcaで参加希望</button><a class="core-link-btn" href="${x.instagramUrl}" target="_blank" onclick="NexcaCore.trackLink('${x.id}','instagram')">Instagram</a><a class="core-link-btn" href="${x.websiteUrl}" target="_blank" onclick="NexcaCore.trackLink('${x.id}','website')">HPを見る</a><a class="core-link-btn" href="${map}" target="_blank" onclick="NexcaCore.trackLink('${x.id}','map')">地図リンク</a>${x.showPhone?`<a class="core-link-btn" href="tel:${x.phoneNumber}" onclick="NexcaCore.trackLink('${x.id}','phone')">電話</a>`:''}</div><button class="cta cta-h" onclick="NexcaCore.openOrganizer('${x.organizerId}')">主催者ページを見る</button><button class="cta cta-y" onclick="shareEv('${x.id}')">共有する</button><div class="core-section-title">説明文</div><p class="desc-txt">${esc(x.description)}</p><div class="core-section-title">詳細情報</div><p class="desc-txt">${esc(x.detailInfo)}</p><div class="core-section-title">ユニーク情報</div><p class="desc-txt">${esc(x.uniqueInfo)}</p><div class="core-section-title">注意事項</div><p class="desc-txt">参加コードは詳細ページには表示されません。現地で確認したコードをマイページから入力してください。</p><div class="core-section-title">参加者の声</div>${reviewsHtml(x.id)}`;$('#drw').classList.add('on');$('#drwbg').classList.add('on');}
  function info(l,v){return `<div class="core-info"><small>${esc(l)}</small><b>${esc(v||'未設定')}</b></div>`;}
  function dateText(x){return x.eventDateType==='evergreen'?x.businessHours:(x.startDate===x.endDate?x.startDate:x.startDate+'〜'+x.endDate)+' / '+x.businessHours;}
  function reviewsHtml(id){const rs=allReviews(id);return rs.length?rs.map(r=>`<div class="core-review"><b>${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)} ${esc(r.displayName||'匿名')}</b><p>${esc(r.comment)}</p></div>`).join(''):'<div class="core-review"><p>まだ参加者の声はありません。</p></div>';}
  function openOrganizer(id){const o=organizers.find(x=>x.id===id);if(!o)return;const posts=listings.filter(x=>x.organizerId===id), active=posts.filter(activeListing), past=posts.filter(x=>!activeListing(x));$('#drwbody').innerHTML=`<button class="bkbtn" onclick="closeDrw()">← 戻る</button><div class="core-org-head" style="--c1:${o.cover[0]};--c2:${o.cover[1]};"><div class="core-org-icon">${o.icon}</div></div><div class="drw-t">${esc(o.name)}</div><div class="core-org-labels">${o.trustLabels.map(l=>`<span class="core-badge">${esc(l)}</span>`).join('')}</div><p class="desc-txt">${esc(o.description)}</p><div class="core-info-grid">${info('ジャンル',o.genres.join('・'))}${info('活動地域',o.area)}${info('住所/エリア',o.address)}${info('いいね合計',posts.reduce((n,x)=>n+likeCount(x),0))}${info('リンククリック合計',linkTotal(id))}${info('参加コード',o.trustLabels.includes('参加コード対応')?'対応':'未対応')}</div><div class="core-links"><a class="core-link-btn" href="${o.instagramUrl}" target="_blank">Instagram</a><a class="core-link-btn" href="${o.websiteUrl}" target="_blank">HP</a>${o.showPhone?`<a class="core-link-btn" href="tel:${o.phoneNumber}">電話</a>`:''}</div><div class="core-section-title">掲載中の投稿</div><div class="core-grid">${active.map(cardHtml).join('')}</div><div class="core-section-title">過去の投稿</div>${past.length?`<div class="core-grid">${past.map(cardHtml).join('')}</div>`:'<div class="core-review"><p>過去投稿はまだありません。</p></div>'}<div class="core-section-title">参加者の声</div>${posts.map(p=>reviewsHtml(p.id)).join('')}`;$('#drw').classList.add('on');$('#drwbg').classList.add('on');}
  function linkTotal(orgId){const c=ls(store.clicks,[]), ids=listings.filter(x=>x.organizerId===orgId).map(x=>x.id);return c.filter(x=>ids.includes(x.listingId)).length;}
  function toggleLike(id){const s=likes(); if(s.has(id)){s.delete(id);toast('気になるを解除しました');}else{s.add(id);toast('気になるに追加しました');try{addPt('気になる',2,false);}catch(e){}}setls(store.likes,[...s]);try{updStats();}catch(e){}renderFeed();if($('#mypage')?.classList.contains('on'))renderMP();}
  function shareEv(id){const x=listings.find(l=>l.id===id);if(!x)return;const url=location.href.split('#')[0]+'#/listing/'+id, text='【'+x.title+'】\n'+x.catchcopy+'\n'+url+'\n#Nexca広島';trackLink(id,'share');if(navigator.share)navigator.share({title:x.title,text,url});else{navigator.clipboard&&navigator.clipboard.writeText(text);toast('URLをコピーしました');}}
  function trackLink(listingId,type){const c=ls(store.clicks,[]);c.push({listingId,type,clickedAt:new Date().toISOString(),userProfile:profile()});setls(store.clicks,c);try{if(window.sb&&window.user)sb.from('event_link_clicks').insert({event_id:listingId,link_type:type,user_id:user.id,clicked_at:new Date().toISOString()}).then(()=>{});}catch(e){}}
  function interest(id){trackLink(id,'nexca_interest');toast('参加希望を記録しました');}
  function openPartM(){goTab('mypage',$$('#nav .nb')[4]);setTimeout(()=>$('#core-code-input')?.focus(),150);}
  function submitCoreCode(){const code=String($('#core-code-input')?.value||'').trim().toUpperCase(), x=listings.find(l=>l.code===code);if(!code){toast('コードを入力してください');return;}if(!x){toast('コードが違います');return;}let rs=redemptions();if(rs.some(r=>r.code===code)){toast('このコードは使用済みです');return;}rs.push({code,listingId:x.id,organizerId:x.organizerId,genre:x.category,redeemedAt:new Date().toISOString(),points:80});setls(store.redemptions,rs);try{addPt('参加コード入力',80,false,'core_code_'+code);}catch(e){}toast('参加済みになりました。参加者の声を投稿できます');renderMP();}
  function submitReview(id){const rating=parseInt($('#core-review-rating')?.value||'5'), comment=($('#core-review-comment')?.value||'').trim(), anon=$('#core-review-anon')?.checked;if(!comment){toast('コメントを入力してください');return;}const p=profile(), rs=reviews();rs.push({id:'rv-'+Date.now(),listingId:id,rating,comment,displayName:anon?'匿名':p.nickname,moderationStatus:'approved',createdAt:new Date().toISOString()});setls(store.reviews,rs);toast('参加者の声を投稿しました');renderMP();}
  function renderMP(){const p=profile(), l=[...likes()].map(id=>listings.find(x=>x.id===id)).filter(Boolean), reds=redemptions();$('#mpname').textContent=p.nickname;$('#mpemail').textContent=p.area+' / '+p.age;$('#mpage').textContent='🎒 '+p.age+' · '+p.area;$('#mpav').innerHTML='👤';$('#gsec').style.display='none';$('#lsec').style.display='block';try{updStats();renderOcGrid();renderLcGrid();}catch(e){}const top=$('#lsec');if(!$('#core-profile-card'))top.insertAdjacentHTML('afterbegin',`<div id="core-profile-card" class="core-profile-card"></div>`);$('#core-profile-card').innerHTML=`<h3>${esc(p.nickname)}</h3><p>${esc(p.age)} / ${esc(p.area)}<br>気になる ${l.length}件・参加コード ${reds.length}件・ポイント ${Math.floor(typeof pts==='number'?pts:0)}pt</p><div class="core-profile-actions"><button onclick="NexcaCore.editProfile()">編集</button><button onclick="openTown()">Nexca Town</button></div>`;
    $('#lgrid').innerHTML=l.length?l.map(cardHtml).join(''):'<div class="empty" style="grid-column:1/-1;"><div class="empty-ic">🤍</div><div class="empty-t">まだ気になる掲載がありません</div></div>';
    $('#wgrid').innerHTML=reds.length?reds.map(r=>{const x=listings.find(l=>l.id===r.listingId);return x?`<div class="core-card" onclick="openDrw('${x.id}')"><div class="core-thumb" style="--c1:${x.colors[0]};--c2:${x.colors[1]};"><span>${x.icon}</span></div><div class="core-card-body"><h3>${esc(x.title)}</h3><p>参加済み: ${esc(r.redeemedAt.slice(0,10))}</p></div></div>`:'';}).join(''):'<div class="empty" style="grid-column:1/-1;"><div class="empty-ic">🎟</div><div class="empty-t">参加コード履歴はまだありません</div></div>';
    if(!$('#core-participation-box'))$('#core-profile-card').insertAdjacentHTML('afterend',`<div id="core-participation-box" class="core-profile-card"></div>`);
    const reviewTargets=reds.map(r=>listings.find(x=>x.id===r.listingId)).filter(Boolean);
    $('#core-participation-box').innerHTML=`<h3>参加コード入力</h3><p>同じコードは1回だけ使用できます。成功すると参加済みになり、参加者の声が投稿できます。</p><div class="core-form"><input id="core-code-input" placeholder="例：VINTAGE50" oninput="this.value=this.value.toUpperCase()"><button class="cta cta-y" onclick="NexcaCore.submitCoreCode()">参加コードを送信</button></div>${reviewTargets.length?`<div class="core-section-title">参加者の声を投稿</div><div class="core-form"><select id="core-review-listing">${reviewTargets.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select><select id="core-review-rating"><option value="5">満足度 5</option><option value="4">満足度 4</option><option value="3">満足度 3</option><option value="2">満足度 2</option><option value="1">満足度 1</option></select><textarea id="core-review-comment" placeholder="行ってみた感想"></textarea><label style="font-size:12px;color:var(--txt2);"><input type="checkbox" id="core-review-anon"> 匿名で表示</label><button class="cta cta-a" onclick="NexcaCore.submitReview(document.getElementById('core-review-listing').value)">投稿する</button></div>`:''}`;
  }
  function editProfile(){ensureSetup();const p=profile();$('#core-nick').value=p.nickname;$('#core-age').value=p.age;$('#core-area').value=p.area;$('#core-setup').classList.add('on');}
  function search(q){state.query=q.trim();renderFlyer();}
  function useLocation(){state.area='現在地周辺';state.near=true;if(navigator.geolocation){navigator.geolocation.getCurrentPosition(pos=>{state.coords={lat:pos.coords.latitude,lng:pos.coords.longitude};toast('現在地周辺で並べ替えます');renderFeed();renderFlyer();},()=>{const p=profile();state.area=p.area;state.near=false;toast('位置情報なし: 登録地域を基準に表示します');renderFeed();renderFlyer();});}else{toast('位置情報に対応していません');}}
  function openFilterSheet(){const areaOpts=areas.concat(['現在地周辺']).map(a=>`<option ${state.area===a?'selected':''}>${a}</option>`).join(''), tagOpts=['all'].concat(tags).map(t=>`<option value="${t}" ${state.tag===t?'selected':''}>${t==='all'?'タグすべて':t}</option>`).join('');$('#drwbody').innerHTML=`<button class="bkbtn" onclick="closeDrw()">← 戻る</button><div class="drw-t">フィルター</div><div class="core-form"><label>日付</label><select onchange="NexcaCore.setFilterRaw('date',this.value)"><option value="all">すべて</option><option value="today">今日</option><option value="tomorrow">明日</option><option value="week">今週</option><option value="weekend">週末</option><option value="month">今月</option></select><label>エリア</label><select onchange="NexcaCore.setFilterRaw('area',this.value)">${areaOpts}</select><label>タグ</label><select onchange="NexcaCore.setFilterRaw('tag',this.value)">${tagOpts}</select></div>`;$('#drw').classList.add('on');$('#drwbg').classList.add('on');}
  function setFilterRaw(k,v){state[k]=v;renderFeed();renderFlyer();}
  function bootCore(){setupNav();maybeShowSetup();renderFeed();renderFlyerTabs();renderFlyer();if($('#mypage')?.classList.contains('on'))renderMP();}
  window.NexcaCore={boot:bootCore,setFilter,setFilterRaw,openFilterSheet,useLocation,search,openOrganizer,trackLink,interest,saveProfile,editProfile,submitCoreCode,submitReview};
  window.renderFeed=renderFeed; window.renderFlyerTabs=renderFlyerTabs; window.renderFlyer=renderFlyer; window.openDrw=openDrw; window.openVOV=openDrw; window.toggleLike=toggleLike; window.shareEv=shareEv; window.renderMP=renderMP; window.openPartM=openPartM;
  document.addEventListener('DOMContentLoaded',()=>setTimeout(bootCore,450));
})();
