(function(){
  'use strict';
  const AREAS=['広島市中区','広島市西区','広島市東区','広島市南区','広島市安佐南区','広島市安佐北区','広島市安芸区','広島市佐伯区','呉市','福山市','尾道市','三原市','東広島市','廿日市市','竹原市','府中市','庄原市','三次市','江田島市','神石高原','世羅','大崎上島','島しょ部'];
  const AGES=['中学生','高校生','大学生','社会人'];
  const $=s=>document.querySelector(s);
  const $$=s=>Array.from(document.querySelectorAll(s));
  const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const css=document.createElement('style');
  css.textContent=`
  .ob-start-btn,.ob-vp,.ob-lbl,.ob-tagline,.ob-logo{animation:none!important;opacity:1!important;pointer-events:auto!important}.ob-start-btn{pointer-events:all!important;touch-action:manipulation}
  .profile-pref-card{margin:0 14px 14px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:13px}.pref-row{display:flex;gap:8px;margin-top:10px}.pref-row select{flex:1;padding:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:10px;color:var(--txt);font-weight:700}.pref-save{padding:10px 13px;background:var(--red);border:0;border-radius:10px;color:white;font-weight:900}
  .nx-video-frame{position:absolute;inset:0;width:100%;height:100%;border:0;background:#050507}.nx-thumb{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:radial-gradient(circle at 50% 35%,rgba(255,255,255,.13),transparent 48%),linear-gradient(135deg,#111827,#050507)}.nx-play{width:72px;height:72px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.5);border:1px solid rgba(255,255,255,.2);font-size:28px;backdrop-filter:blur(10px)}
  .gg-panel{display:flex;flex-direction:column;gap:12px}.gg-field{background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.075);border-radius:12px;padding:11px}.gg-label{font-size:10px;font-weight:900;color:var(--dim);letter-spacing:1px;margin-bottom:8px}.gg-chips{display:flex;gap:7px;flex-wrap:wrap}.gg-chip{padding:8px 10px;border-radius:999px;background:rgba(255,255,255,.05);border:1.5px solid rgba(255,255,255,.08);font-size:11px;font-weight:800;color:var(--txt);cursor:pointer}.gg-chip.on{background:rgba(230,57,70,.18);border-color:var(--red);box-shadow:0 0 18px rgba(230,57,70,.18)}.gg-btn.destiny{width:100%;padding:15px;background:linear-gradient(135deg,#E63946,#ffbe00);box-shadow:0 0 24px rgba(230,57,70,.35)}.gg-spin{padding:18px;text-align:center;font-family:var(--font-en);font-size:20px;letter-spacing:2px;color:var(--yellow);animation:pulse .35s infinite alternate}.gg-result-card{border-radius:16px;padding:16px;background:linear-gradient(160deg,rgba(255,255,255,.09),rgba(255,255,255,.03));border:1px solid rgba(255,255,255,.12)}.gg-rarity{display:inline-flex;padding:3px 10px;border-radius:999px;font-size:10px;font-weight:900;margin-bottom:8px}.gg-rarity.normal{background:rgba(255,255,255,.08);color:var(--txt2)}.gg-rarity.rare{background:rgba(77,159,255,.16);color:var(--blue)}.gg-rarity.legendary{background:rgba(255,190,0,.2);color:var(--yellow);box-shadow:0 0 22px rgba(255,190,0,.2)}.gg-actions{display:flex;gap:8px;margin-top:12px}.gg-actions button,.gg-actions a{flex:1;text-align:center;text-decoration:none;padding:10px;border-radius:10px;border:0;font-size:12px;font-weight:900;color:white;background:rgba(255,255,255,.08);font-family:var(--font-jp)}
  .rank-tabs{display:flex;gap:6px;overflow-x:auto;margin-bottom:10px}.rank-tab{border:0;border-radius:999px;padding:7px 11px;background:rgba(255,255,255,.06);color:var(--dim);font-size:11px;font-weight:900}.rank-tab.on{background:var(--red);color:white}.my-rank{margin-bottom:10px;padding:11px;border-radius:12px;background:rgba(255,190,0,.08);border:1px solid rgba(255,190,0,.18);font-size:12px;font-weight:900;color:var(--yellow)}
  .gacha-legendary-burst{animation:nxBurst 1.4s ease both}@keyframes nxBurst{35%{box-shadow:0 0 0 999px rgba(255,190,0,.16)}}@media (orientation:landscape){#nav{height:50px}.screen{bottom:50px}.sbot{bottom:8px}.srt{bottom:62px}.stitle{font-size:17px}.ob-logo{font-size:40px}}`;
  document.head.appendChild(css);

  function publicId(id){return String(id||'').replace(/^db_/,'');}
  function moneyCap(s){if(!s||s==='制限なし')return 999999;if(s==='無料')return 0;return Number(String(s).replace(/\D/g,''))||999999;}
  function videoHtml(ev){
    const u=String(ev.video_url||ev.vid||'');
    if(!u)return `<div class="nx-thumb"><div class="nx-play">${safe(ev.em||'▶')}</div></div>`;
    let src=''; const yt=u.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/|embed\/))([A-Za-z0-9_-]{6,})/);
    if(yt)src=`https://www.youtube.com/embed/${yt[1]}?playsinline=1&mute=1&rel=0`;
    else if(/instagram\.com\//.test(u)){const id=(u.split('/p/')[1]||u.split('/reel/')[1]||'').split('/')[0]; if(id)src=`https://www.instagram.com/p/${id}/embed`;}
    else if(/tiktok\.com\//.test(u))src=u.replace('/video/','/embed/v2/');
    return src?`<iframe class="nx-video-frame" loading="lazy" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen src="${safe(src)}"></iframe>`:`<div class="nx-thumb"><div class="nx-play">▶</div></div>`;
  }
  function extendData(){
    if(typeof GS!=='undefined'){GS.cafe={bg:'rgba(76,175,80,.13)',bd:'rgba(76,175,80,.35)',c:'#8ee6a0'};GS.vintage={bg:'rgba(255,190,0,.13)',bd:'rgba(255,190,0,.35)',c:'#ffcf4d'};}
    if(typeof OC!=='undefined'&&!OC.ネクスケ)OC.ネクスケ={color:'#E63946',genre:'event',kuchi:'次、行ってみよ。',pers:'Nexcaそのものの好奇心を持つ案内役。',weak:'予定を詰め込みすぎる。',compat:'フワリ',cd:'勢いと観察眼の相性がいい。',catch:'まだ知らない広島を、今日の予定に変える。',mbti:{E:70,N:88,F:60,P:90},strengths:['発見力','案内力','巻き込み力'],growth:'休む時間も予定に入れて。',lvUp:[]};
    if(typeof MISSIONS!=='undefined'&&Array.isArray(MISSIONS)&&MISSIONS.length<15){
      [['m6','カフェを1件保存する','カフェジャンルで行きたい登録',10],['m7','古着スポットを探す','古着ジャンルを閲覧',10],['m8','友達に1件シェアする','イベントをSNS共有',10],['m9','地図リンクを開く','詳細から地図を確認',8],['m10','今週のイベントを見る','日付で絞り込む',8],['m11','グループガチャを回す','条件を選んで運命を回す',15],['m12','マイ広島に建物を置く','街を育てる',15],['m13','キャラEXPを増やす','参加証明または街で交流',20],['m14','ランキングを見る','順位を確認',5],['m15','検索履歴を作る','検索を使う',5]].forEach(x=>MISSIONS.push({id:x[0],name:x[1],sub:x[2],pt:x[3],progress:0,goal:1,done:false}));
    }
    if(typeof GACHA!=='undefined'){
      GACHA.Common=(GACHA.Common||[]).concat(['家の近くで空を30秒見る','今日の予定に小さな寄り道を1つ足す','最近よかった店をメモする'].map(text=>({text,ev:'小さな行動変化は習慣化しやすい',type:'家',pts:15})));
      GACHA.Uncommon=(GACHA.Uncommon||[]).concat(['気になるイベントを1つ友達に送る','知らない通りを1本だけ歩く','カフェでおすすめを聞く'].map(text=>({text,ev:'新奇探索は気分転換を助ける',type:'外',pts:25})));
      GACHA.Rare=(GACHA.Rare||[]).concat(['本通り周辺で初めての店に入る','川沿いで10分だけスマホをしまう'].map(text=>({text,ev:'環境への注意はマインドフルネス効果を持つ',type:'外',pts:40})));
      GACHA.Epic=(GACHA.Epic||[]).concat([{text:'古着屋を3軒はしごしてテーマを決める',ev:'共同計画は達成感を高める',type:'外',pts:60}]);
      GACHA.Legendary=(GACHA.Legendary||[]).concat([{text:'朝から夜まで広島を1本の物語として歩く',ev:'長時間の新奇体験は自己効力感を刺激する',type:'外',pts:120}]);
    }
  }
  const seeds=['本通りの裏路地をあてもなく歩く','袋町公園でコンビニ飯を食べながら話す','喫茶店に入って長居する','路面電車に乗ってどこかで降りる','元安川沿いをゆっくり歩く','川沿いのベンチに座って何もしない','知らない喫茶店で本を読む','比治山から夕暮れの広島を見下ろす','宇品港で海を眺めながら昔話をする','原爆ドームが見える川沿いで語る','フェリーのデッキで海風を浴びる','平和公園の誰もいない早朝を歩く','太田川を北に向かって歩く','路面電車で終点まで行ってUターン','本通りの古着屋を3軒はしご','広島城の周りをランニング','宮島で大鳥居まで歩く','大和ミュージアムを見学して海沿いを歩く','じゃんけんで次の角を曲がる方向を決めて歩く','コンビニで一番変なものを買って食べる','路面電車の中で広島弁だけで話す','宇品港の工場夜景を2人で見る','元安川沿いをスマホをしまって歩く','夜の平和公園で並んで座る','干潮の砂浜を大鳥居まで2人で歩く','千光寺公園から夜景を見る','尾道の細い路地を2人で迷子になる','次のバスに乗って終点まで行く','地図を見ずに勘だけで1時間歩く','一度も降りたことのない駅で降りる','始発電車に乗って海を見に行く'];
  const moods=['まったり','エモい','アクティブ','ボケ','ロマンチック','非日常','おまかせ'];
  const plans=[]; AREAS.forEach(area=>moods.forEach(mood=>seeds.forEach((seed,i)=>{if(plans.length<340)plans.push({title:`${area}で${seed}`,desc:`${mood}気分に合わせて、${area}周辺で無理なくできる体験。危険な場所・私有地・廃墟は使わない。`,area,mood,time:['朝','午前','昼','午後','夕方','夜'][i%6],budget:[0,300,500,1000,2000,3000,5000,10000][i%8],indoor:i%3===0,outdoor:i%3!==0,map:`https://maps.google.com/?q=${encodeURIComponent(area)}`});})));
  const dayPlans=Array.from({length:24},(_,i)=>({title:`${AREAS[i%AREAS.length]} 1日ネクスカ旅 ${i+1}`,desc:'午前：川沿いか商店街を歩く → 昼：地元の店でごはん → 午後：イベントか古着/カフェを巡る → 夜：明るい駅周辺で締める。',area:AREAS[i%AREAS.length],mood:moods[i%moods.length],time:'1日',budget:[2000,3000,5000,10000][i%4],indoor:i%2===0,outdoor:true,map:`https://maps.google.com/?q=${encodeURIComponent(AREAS[i%AREAS.length])}`}));

  function hydrateGroupGacha(){
    const old=$('#group-gacha-card')||$('.gg-card'); if(!old)return;
    old.id='group-gacha-card';
    old.innerHTML='<div style="font-family:var(--font-en);font-size:15px;letter-spacing:1px;margin-bottom:14px;">GROUP GACHA</div><div id="gg-v2-panel" class="gg-panel"></div><button class="gg-btn destiny" onclick="drawGroupGacha()">運命を回す</button><div class="gg-result" id="gg-result"></div>';
    const field=(key,label,items,multi,max=99)=>`<div class="gg-field"><div class="gg-label">${label}</div><div class="gg-chips" data-key="${key}" data-multi="${multi?1:0}" data-max="${max}">${items.map((x,i)=>`<button class="gg-chip ${!multi&&i===0?'on':''}" data-val="${x}" onclick="selChip(this)">${x}</button>`).join('')}</div></div>`;
    $('#gg-v2-panel').innerHTML=field('count','人数',['1人','2人','3人','4人','5人以上'],false)+field('scene','シチュエーション',['友達','デート','家族','旅行','1人時間'],false)+field('time','時間帯',['朝','午前','昼','午後','夕方','夜','深夜'],true)+field('area','エリア',AREAS,true)+field('budget','予算',['無料','〜300円','〜500円','〜1000円','〜2000円','〜3000円','〜5000円','〜10000円','制限なし'],false)+field('mood','ムード',moods,true,3)+'<div class="gg-field"><div class="gg-label">天気</div><div style="font-size:11px;color:var(--dim);">現在地の天気で屋内/屋外を自動調整。取得できない場合は安全側で選出します。</div></div>';
  }
  window.selChip=function(btn){const wrap=btn.parentElement,multi=wrap.dataset.multi==='1',max=Number(wrap.dataset.max||99);if(multi){if(!btn.classList.contains('on')&&wrap.querySelectorAll('.gg-chip.on').length>=max){toast('最大'+max+'つまで選べます');return;}btn.classList.toggle('on');}else{wrap.querySelectorAll('.gg-chip').forEach(b=>b.classList.remove('on'));btn.classList.add('on');}};
  function vals(k){const w=$(`.gg-chips[data-key="${k}"]`);return w?$$(`.gg-chips[data-key="${k}"] .gg-chip.on`).map(b=>b.dataset.val):[];}
  window.drawGroupGacha=function(){
    const el=$('#gg-result'); if(!el)return;
    let times=vals('time'); if(!times.length)times=['昼','午後','夕方'];
    const count=vals('count')[0]||'1人', scene=vals('scene')[0]||'友達', areas=vals('area').length?vals('area'):['広島市中区'], budget=vals('budget')[0]||'制限なし', moodVals=vals('mood').length?vals('mood'):['おまかせ'];
    if(['中学生','高校生'].includes(age)&&times.includes('深夜')){times=times.filter(t=>t!=='深夜');toast('中高生向けに深夜プランを外しました');}
    el.style.display='block'; el.innerHTML='<div class="gg-spin">ROULETTE...</div>';
    setTimeout(()=>el.innerHTML='<div class="gg-spin">DRUM ROLL...</div>',3000);
    setTimeout(()=>{
      const r=Math.random()*100, rarity=r<5?'legendary':r<30?'rare':'normal', pool=rarity==='legendary'?dayPlans:plans;
      const cap=moneyCap(budget);
      let cand=pool.filter(p=>areas.some(a=>p.area.includes(a)||a.includes(p.area))&&moodVals.some(m=>m==='おまかせ'||p.mood===m)&&times.some(t=>p.time===t||p.time==='1日')&&p.budget<=cap);
      if(count==='1人'&&times.includes('深夜'))cand=cand.filter(p=>p.indoor);
      const evHit=(typeof EVS!=='undefined'?EVS:[]).find(ev=>!ev.isOfficial&&areas.some(a=>String(ev.loc||'').includes(a.replace('広島市',''))));
      const p=evHit&&rarity!=='legendary'?{title:evHit.title,desc:'Nexca掲載イベントが条件に合ったので優先表示。'+evHit.desc,area:evHit.loc,mood:moodVals[0],time:evHit.ts||times[0],budget:evHit.price,map:`https://maps.google.com/?q=${encodeURIComponent(evHit.addr||evHit.loc)}`}:(cand[Math.floor(Math.random()*cand.length)]||pool[Math.floor(Math.random()*pool.length)]);
      window.lastGroupPlan=p;
      el.innerHTML=`<div class="gg-result-card"><div class="gg-rarity ${rarity}">${rarity==='legendary'?'激レア 1日プラン':rarity==='rare'?'レア':'ノーマル'}</div><div style="font-size:17px;font-weight:900;margin-bottom:6px;">${safe(p.title)}</div><div style="font-size:12px;color:var(--txt2);line-height:1.8;">${safe(p.desc)}</div><div style="font-size:11px;color:var(--dim);margin-top:10px;">${safe(scene)} · ${safe(count)} · ${safe(budget)} · ${safe(p.area)}</div><div class="gg-actions"><a href="${p.map}" target="_blank">地図</a><button onclick="addPt('今日これをやる',10,false);toast('今日のプランに決定！ +10pt')">今日これをやる</button><button onclick="shareGroupPlan()">シェア</button></div></div>`;
      const m=(typeof MISSIONS!=='undefined'?MISSIONS:[]).find(x=>x.id==='m11'); if(m&&!m.done){m.done=true;m.progress=1;addPt('ミッション達成：'+m.name,m.pt,false);}
    },5000);
  };
  window.shareGroupPlan=function(){const p=window.lastGroupPlan;if(!p)return;const text=`Nexcaグループガチャ結果：${p.title}\n${p.desc}\n#Nexca広島`;navigator.share?navigator.share({title:'Nexcaグループガチャ',text,url:location.href}).catch(()=>{}):(navigator.clipboard&&navigator.clipboard.writeText(text),toast('コピーしました！'));};

  function overrideCore(){
    if(typeof EVS==='undefined')return;
    EVS.forEach(e=>{if(e.genre==='furugiya')e.genre=e.g='vintage'; if(e.gl==='ワークショップ'||e.g==='learn'||e.g==='volunteer'){e.g=e.genre='event';e.gl='イベント・体験';e.ge='🎉';} if(e.genre==='cafe'){e.g='cafe';e.gl='カフェ';e.ge='☕';} if(e.genre==='vintage'){e.g='vintage';e.gl='古着';e.ge='👗';}});
    window.mkSlide=function(ev,i){const s=document.createElement('div');s.className='slide dn';s.dataset.i=i;const gs=(typeof GS!=='undefined'&&(GS[ev.g]||GS.event))||{bg:'rgba(230,57,70,.12)',bd:'rgba(230,57,70,.35)',c:'#ff8fa0'}, lk=likes.has(ev.id), wnt=wants.has(ev.id), id=ev.id;s.innerHTML=`<div class="sbg" style="background:${safe(ev.bg)};">${videoHtml(ev)}</div><div class="sovl"></div><div class="srt"><button class="sact${lk?' lk':''}" id="lb-${id}" onclick="toggleLike('${id}')"><div class="sact-c">${lk?'❤️':'🤍'}</div><div class="sact-l" id="lc-${id}">${ev.like_count||0}</div></button><button class="sact${wnt?' wnt':''}" id="wb-${id}" onclick="toggleWant('${id}')"><div class="sact-c">${wnt?'⭐':'☆'}</div><div class="sact-l">行きたい</div></button><button class="sact" onclick="shareEv('${id}')"><div class="sact-c">📤</div><div class="sact-l">シェア</div></button></div><div class="sbot">${ev.charKey?`<div class="schar-badge"><span style="font-size:14px;">${safe(ev.charEmoji||'🎭')}</span><span style="font-size:10px;font-weight:700;">${safe(ev.charName||ev.charKey)}</span></div>`:''}<div class="sgtag" style="background:${gs.bg};border-color:${gs.bd};color:${gs.c};">${safe(ev.ge)} ${safe(ev.gl)}</div><div class="stitle">${safe(ev.title)}</div><div class="smeta"><span class="smeta-i">📅 ${safe(ev.ds||ev.ts||'随時')}</span><span class="smeta-i">📍 ${safe(ev.loc)}</span></div><button class="sdbtn" onclick="openDrw('${id}')">詳細情報・参加コード</button></div><div class="shint">↑ スワイプで次へ</div>`;return s;};
    window.renderGenreOpts=function(){const cfg=[['all','すべて','全ジャンル表示','📍'],['vintage','古着','ヴィンテージ・セレクト','👗'],['cafe','カフェ','喫茶・コーヒー・休憩','☕'],['event','イベント・体験','おでかけ・フェス・ワークショップ','🎉']];const el=$('#fm-gopts');if(el)el.innerHTML=cfg.map(c=>`<div class="fm-gopt${genre===c[0]?' on':''}" data-g="${c[0]}" onclick="pickGenre(this)"><div class="fm-gopt-ic">${c[3]}</div><div><div class="fm-gopt-n">${c[1]}</div><div class="fm-gopt-sub">${c[2]}</div></div><div class="fm-gopt-chk">✓</div></div>`).join('');};
    window.renderFlyerTabs=function(){const cfg=[['all','すべて','📍'],['vintage','古着','👗'],['cafe','カフェ','☕'],['event','イベント・体験','🎉']];const el=$('#ftabs-wrap');if(el)el.innerHTML=cfg.map(c=>`<div class="ftab${flyG===c[0]?' on':''}" data-g="${c[0]}" onclick="setFlyG(this)">${c[2]} ${c[1]}</div>`).join('');};
    window.pickGenre=function(el){$$('.fm-gopt').forEach(b=>b.classList.remove('on'));el.classList.add('on');genre=el.dataset.g;const lb={all:'すべて',vintage:'古着',cafe:'カフェ',event:'イベント・体験'};$('#fl').textContent=lb[genre]||'すべて';renderFeed();closeFM();};
    window.renderFeed=function(){let src=feedMode==='official'?EVS.filter(e=>e.isOfficial):EVS.filter(e=>!e.isOfficial&&(!e.age||!age||e.age.includes(age)));if(feedMode!=='official'&&genre&&genre!=='all')src=src.filter(e=>e.g===genre||e.genre===genre||(genre==='event'&&!['cafe','vintage'].includes(e.g)));if(feedMode==='recommend')src=src.slice().sort((a,b)=>getRecScore(b)-getRecScore(a));fevs=src;idx=0;const st=$('#stack');st.innerHTML='';if(!src.length){st.innerHTML='<div class="empty" style="position:absolute;inset:0;display:flex;"><div class="empty-ic">🔍</div><div class="empty-t">この条件のイベントはありません</div></div>';return;}src.forEach((ev,i)=>st.appendChild(mkSlide(ev,i)));updPos();};
    window.openDrw=function(id){const ev=EVS.find(e=>e.id===id);if(!ev)return;const gs=(typeof GS!=='undefined'&&(GS[ev.g]||GS.event))||{bg:'rgba(230,57,70,.12)',c:'#ff8fa0'}, map=`https://maps.google.com/?q=${encodeURIComponent(ev.addr||ev.loc)}`, cd=ev.charKey&&OC?OC[ev.charKey]:null, info=cd?calcCprog(charExp[ev.charKey]||0):null;const link=(cls,label,url,type)=>url?`<a class="cta ${cls}" href="${safe(url)}" target="_blank" onclick="trackLinkClick('${ev.id}','${type}')">${label}</a>`:'';$('#drwbody').innerHTML=`<button class="bkbtn" onclick="closeDrw()">← 動画フィードに戻る</button><div class="drw-t">${safe(ev.title)}</div><div class="drw-gt" style="background:${gs.bg};color:${gs.c};">${safe(ev.ge)} ${safe(ev.gl)}</div><div class="drw-tags">${(ev.tags||[]).map(t=>`<div class="drw-tag">${safe(t)}</div>`).join('')}</div>${cd?`<div class="cblk"><span style="font-size:34px;">${safe(ev.charEmoji||'🎭')}</span><div style="flex:1;"><div class="cblk-name" style="color:${cd.color};">${safe(ev.charName||ev.charKey)}</div><div class="cblk-desc">${safe(ev.charDesc||cd.catch)}</div><div class="clvbar"><div class="clvfill" style="width:${info.pct}%;background:${cd.color};"></div></div><div style="font-size:9px;color:var(--dim);margin-top:3px;">Lv${info.lv} · EXP ${info.cur}/${info.need}</div></div></div>`:''}<div class="ic"><div class="ic-l">DATE / TIME</div><div class="ic-v">${safe(ev.ds||'随時')} ${safe(ev.ts||'')}</div></div><div class="ic"><div class="ic-l">LOCATION</div><div class="ic-v">${safe(ev.loc)}<br>${safe(ev.addr||'')}</div><a href="${map}" target="_blank" onclick="trackLinkClick('${ev.id}','map')" class="gmapbtn">🗺️ Googleマップで開く</a></div><div class="ic"><div class="ic-l">FEE</div><div class="ic-v">${safe(ev.price||'無料')}</div></div><p class="desc-txt">${safe(ev.desc)}</p><div class="ctas"><button class="cta cta-y" onclick="openPartM('${ev.id}')">参加コードを入力する</button><a class="cta cta-m" href="${map}" target="_blank" onclick="trackLinkClick('${ev.id}','map')">🗺️ 地図</a>${link('cta-i','Instagram',ev.ig,'instagram')}${link('cta-h','公式サイト',ev.website_url||ev.hp,'website')}${link('cta-a','予約する',ev.booking_url||ev.rev,'booking')}<button class="cta cta-h" onclick="shareLine('${ev.id}')">LINEでシェア</button></div>`;$('#drw').classList.add('on');$('#drwbg').classList.add('on');};
  }
  window.trackLinkClick=async function(id,type){try{await sb.from('event_link_clicks').insert({event_id:publicId(id),link_type:type,click_type:type,user_id:(typeof user!=='undefined'&&user)?user.id:null,clicked_at:new Date().toISOString()});}catch(e){}};
  window.shareLine=function(id){const ev=EVS.find(e=>e.id===id);if(!ev)return;trackLinkClick(id,'line_share');window.open(`https://social-plugins.line.me/lineit/share?url=${encodeURIComponent(location.href.split('#')[0]+'#/event/'+id)}&text=${encodeURIComponent(ev.title+'｜Nexcaで見つけた広島の体験')}`,'_blank');};
  const originalSearch=window.doSearch; window.doSearch=function(q){q=String(q||'').trim();if(q){const h=JSON.parse(localStorage.getItem('nx_search_history')||'[]').filter(x=>x!==q);h.unshift(q);localStorage.setItem('nx_search_history',JSON.stringify(h.slice(0,8)));} if(originalSearch)originalSearch(q);};
  async function hasGachaToday(){const d=new Date().toISOString().slice(0,10);if((typeof user!=='undefined'&&user)){try{const r=await sb.from('gacha_logs').select('id').eq('user_id',user.id).eq('date',d).maybeSingle();if(r.data)return true;}catch(e){}}return localStorage.getItem('nx_gacha_date')===d;}
  async function recordGachaToday(){const d=new Date().toISOString().slice(0,10);localStorage.setItem('nx_gacha_date',d);if((typeof user!=='undefined'&&user)){try{await sb.from('gacha_logs').insert({user_id:user.id,date:d,created_at:new Date().toISOString()});}catch(e){}}}
  window.openGacha=async function(){if(await hasGachaToday()){toast('本日のガチャは使用済みです');return;}const weights={Common:45,Uncommon:27,Rare:17,Epic:8,Legendary:3};let rand=Math.random()*100,rarity='Common',cum=0;for(const r of Object.keys(weights)){cum+=weights[r];if(rand<cum){rarity=r;break;}}const pool=GACHA[rarity]||GACHA.Common;window.gMission=pool[Math.floor(Math.random()*pool.length)];gMission.rarity=rarity;await recordGachaToday();if(rarity==='Legendary'){document.body.classList.add('gacha-legendary-burst');setTimeout(()=>document.body.classList.remove('gacha-legendary-burst'),1600);}const icons={Common:'🎴',Uncommon:'🌟',Rare:'💎',Epic:'🔮',Legendary:'🌈'}, cls={Common:'gr-c',Uncommon:'gr-u',Rare:'gr-r',Epic:'gr-e',Legendary:'gr-l'};$('#gr-icon').textContent=icons[rarity];$('#gr-rarity').className='gr-rarity '+cls[rarity];$('#gr-rarity').textContent=rarity;$('#gr-type').textContent=gMission.type==='家'?'🏠 家でできるミッション':'🌿 外でできるミッション';$('#gr-text').textContent=gMission.text;$('#gr-evidence').textContent='📚 '+gMission.ev;$('#gacha-ov').classList.add('on');};
  const oldAccept=window.acceptGacha; window.acceptGacha=function(){if(!window.gMission)return oldAccept&&oldAccept();const txt=`Nexcaガチャで「${gMission.text}」を引いた！ #Nexca広島`;addPt('ガチャミッション達成',gMission.pts,false);navigator.share&&navigator.share({title:'Nexcaガチャ結果',text:txt,url:location.href}).catch(()=>{});closeGacha();toast('ミッション受け取り！頑張ろう');};
  window.renderRank=async function(){const el=$('#rank-list');if(!el)return;el.innerHTML=`<div class="rank-tabs"><button class="rank-tab on" onclick="renderRankScope('week',this)">週間</button><button class="rank-tab" onclick="renderRankScope('month',this)">月間</button><button class="rank-tab" onclick="renderRankScope('all',this)">全期間</button><button class="rank-tab" onclick="renderRankScope('area',this)">エリア別</button></div><div id="rank-scope-list"></div>`;renderRankScope('week',el.querySelector('.rank-tab'));};
  window.renderRankScope=async function(scope,btn){$$('.rank-tab').forEach(b=>b.classList.remove('on'));btn&&btn.classList.add('on');const box=$('#rank-scope-list');box.innerHTML='<div style="text-align:center;padding:18px;color:var(--dim);">読み込み中...</div>';try{let q=sb.from('rankings').select('*').order('total_points',{ascending:false}).limit(50);if(scope==='area'&&city)q=q.eq('city',city);const r=await q,data=r.data||[];if(!data.length){box.innerHTML='<div class="empty"><div class="empty-ic">🏆</div><div class="empty-t">まだランキングデータがありません</div></div>';return;}const me=(typeof user!=='undefined'&&user)?data.findIndex(x=>x.user_id===user.id):-1;box.innerHTML=(me>=0?`<div class="my-rank">あなたの順位：${me+1}位 · ${data[me].total_points||0}pt</div>`:'')+data.slice(0,10).map((r,i)=>`<div class="rank-item"><div class="rank-num${i===0?' gold':i===1?' silver':i===2?' bronze':''}">${['🥇','🥈','🥉'][i]||i+1}</div><div class="rank-name">${safe(r.nickname||'ユーザー')}<div style="font-size:9px;color:var(--dim);">${safe(r.city||'広島')}</div></div><div class="rank-pt">${r.total_points||0}pt</div></div>`).join('');}catch(e){box.innerHTML='<div class="empty"><div class="empty-ic">🏆</div><div class="empty-t">取得できませんでした</div></div>';}}
  function addProfilePrefs(){const l=$('#lsec');if(!l||$('#profile-pref-card'))return;const div=document.createElement('div');div.id='profile-pref-card';div.className='profile-pref-card';div.innerHTML=`<div style="font-size:13px;font-weight:900;">地域・年齢層</div><div style="font-size:11px;color:var(--dim);margin-top:3px;">マイページでいつでも変更できます</div><div class="pref-row"><select id="pref-age">${AGES.map(a=>`<option ${a===age?'selected':''}>${a}</option>`).join('')}</select><select id="pref-city">${AREAS.concat(['その他・県外']).map(c=>`<option ${c===city?'selected':''}>${c}</option>`).join('')}</select><button class="pref-save" onclick="saveProfilePrefs()">保存</button></div>`;l.insertBefore(div,l.firstChild);}
  window.saveProfilePrefs=async function(){age=$('#pref-age').value;city=$('#pref-city').value;localStorage.setItem('nx_age',age);localStorage.setItem('nx_city',city);localStorage.setItem('nx_onboarding_done','1');updateAB&&updateAB();renderMP&&renderMP();renderFeed&&renderFeed();if((typeof user!=='undefined'&&user)){try{await sb.from('profiles').upsert({user_id:user.id,age_group:age,city:city,updated_at:new Date().toISOString()},{onConflict:'user_id'});}catch(e){}}toast('プロフィールを更新しました');};
  const oldRenderMP=window.renderMP; window.renderMP=function(){oldRenderMP&&oldRenderMP();addProfilePrefs();};
  async function applyProfile(){if((typeof user!=='undefined'&&user)){try{const p=await sb.from('profiles').select('age_group,city,town_data,char_exp,total_points').eq('user_id',user.id).maybeSingle();if(p.data){if(p.data.age_group){age=p.data.age_group;localStorage.setItem('nx_age',age);}if(p.data.city){city=p.data.city;localStorage.setItem('nx_city',city);}if(p.data.town_data)townData=p.data.town_data;if(p.data.char_exp)charExp=Object.assign(charExp||{},p.data.char_exp);localStorage.setItem('nx_onboarding_done','1');$('#ob')&&$('#ob').classList.add('hide');$('#ab')&&($('#ab').style.display='flex');updateAB&&updateAB();boot&&boot();renderMP&&renderMP();}}catch(e){}}else if(!localStorage.getItem('nx_onboarding_done')&&!localStorage.getItem('nx_prereg')){$('#ob')&&$('#ob').classList.remove('hide');}}
  const oldStart=window.startApp; window.startApp=function(){localStorage.setItem('nx_onboarding_done','1');oldStart&&oldStart();if((typeof user!=='undefined'&&user))saveProfilePrefs();};
  const oldPre=window.submitPreReg; window.submitPreReg=async function(){await (oldPre&&oldPre());localStorage.setItem('nx_onboarding_done','1');};
  function installNexcaGameLayer(){
    const gameCss=document.createElement('style');
    gameCss.textContent=`
      .nx-char-svg{width:44px;height:44px;border-radius:14px;display:inline-flex;align-items:center;justify-content:center;background:rgba(255,255,255,.06);box-shadow:0 0 22px var(--c,rgba(255,255,255,.2));overflow:hidden}
      .nx-summon-stage{position:absolute;inset:0;background:radial-gradient(circle at 50% 45%,var(--c,rgba(255,255,255,.3)),transparent 34%),rgba(0,0,0,.92);animation:nxSummonBg 2.4s ease both;z-index:-1}
      @keyframes nxSummonBg{0%{filter:brightness(.2)}45%{filter:brightness(1.8)}100%{filter:brightness(1)}}
      .nx-evo-title{font-family:var(--font-en);font-size:13px;letter-spacing:3px;color:var(--yellow);margin-bottom:8px;text-align:center}
      .nx-town-road{position:absolute;left:0;right:0;bottom:20%;height:34%;background:linear-gradient(120deg,transparent 0 18%,rgba(255,255,255,.08) 18% 24%,transparent 24% 45%,rgba(255,255,255,.07) 45% 52%,transparent 52%);opacity:.7}
      .nx-town-building{position:absolute;transform:translate(-50%,-50%);font-size:28px;filter:drop-shadow(0 8px 10px rgba(0,0,0,.45))}
      .nx-town-chat{position:absolute;left:50%;top:-22px;transform:translateX(-50%);white-space:nowrap;background:rgba(0,0,0,.68);border:1px solid rgba(255,255,255,.16);border-radius:999px;padding:3px 8px;font-size:9px;color:white}
      .nx-gacha-cinema{position:fixed;inset:0;z-index:920;display:none;align-items:center;justify-content:center;background:radial-gradient(circle,rgba(255,190,0,.18),rgba(0,0,0,.96) 56%);font-family:var(--font-en);font-size:26px;letter-spacing:4px;color:var(--yellow)}
      .nx-gacha-cinema.on{display:flex;animation:nxCine 2.3s ease both}@keyframes nxCine{0%{opacity:0;transform:scale(1.1)}25%,80%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(.96)}}`;
    document.head.appendChild(gameCss);
    if(!document.getElementById('nx-gacha-cinema')){const g=document.createElement('div');g.id='nx-gacha-cinema';g.className='nx-gacha-cinema';g.textContent='NEXCA FATE DROP';document.body.appendChild(g);}
  }
  const OFFICIAL_CHARS={
    'アガル':{genre:'event',color:'#ff4d4d',icon:'🔥',evo:['火花のアガル','熱風のアガル','爆祭のアガル'],line:['よし、今日を動かすぞ。','その一歩、ちゃんと熱になってる。','街ごと上げていこう。']},
    'ツムギ':{genre:'vintage',color:'#ffd54a',icon:'🧵',evo:['目利きのツムギ','記憶編みのツムギ','時装のツムギ'],line:['その服、物語を持ってる。','好きはちゃんと積み重なる。','君の審美眼、進化してる。']},
    'ヌクミ':{genre:'cafe',color:'#6ee7a8',icon:'☕',evo:['ひだまりのヌクミ','深煎りのヌクミ','憩界のヌクミ'],line:['まあ座って、息をしよう。','休むのも前に進むこと。','ここが君の充電スポット。']},
    'テクル':{genre:'event',color:'#7c8cff',icon:'⚙️',evo:['試作のテクル','発明のテクル','未来図のテクル'],line:['失敗はデータ。次いこ。','発見、ちゃんと記録した？','君の工夫が街を変える。']},
    'コネル':{genre:'event',color:'#c084fc',icon:'🫧',evo:['糸口のコネル','結び目のコネル','縁環のコネル'],line:['つながりは小さく始まる。','話してみる価値、あるかも。','その縁、育ってきたね。']},
    'フワリ':{genre:'cafe',color:'#67d8ff',icon:'🪽',evo:['そよぎのフワリ','雲間のフワリ','風詠みのフワリ'],line:['急がなくていいよ。','見えてるもの、言葉にしてみて。','軽やかに、でも確かに。']},
    'ネクスケ':{genre:'event',color:'#e63946',icon:'🧭',evo:['案内人ネクスケ','開拓者ネクスケ','Nexcaの羅針盤'],line:['次の広島、見つけに行こ。','今日の選択が地図になる。','君がNexcaを進めてる。']},
    'カゲ':{genre:'event',color:'#9aa0ff',icon:'🌙',evo:['月影のカゲ','静守のカゲ','夜導のカゲ'],line:['静かな参加も、ちゃんと力だ。','見えないところで街は育つ。','君の一歩、誰かを支えてる。']}
  };
  function charForEvent(ev){if(ev.charKey&&OFFICIAL_CHARS[ev.charKey])return ev.charKey;if(ev.g==='vintage'||ev.genre==='vintage')return 'ツムギ';if(ev.g==='cafe'||ev.genre==='cafe')return 'ヌクミ';const pool=['アガル','ネクスケ','コネル','テクル','カゲ'];return pool[Math.abs(String(ev.id||ev.title).split('').reduce((a,c)=>a+c.charCodeAt(0),0))%pool.length];}
  function charSvg(name,size=72){const c=OFFICIAL_CHARS[name]||OFFICIAL_CHARS.ネクスケ;const label=encodeURIComponent(c.icon);return `<svg viewBox="0 0 120 120" width="${size}" height="${size}" aria-label="${safe(name)}"><defs><radialGradient id="g"><stop offset="0" stop-color="#fff"/><stop offset=".42" stop-color="${c.color}"/><stop offset="1" stop-color="#111"/></radialGradient></defs><circle cx="60" cy="60" r="54" fill="url(#g)" opacity=".95"/><circle cx="42" cy="52" r="7" fill="#08080a"/><circle cx="78" cy="52" r="7" fill="#08080a"/><path d="M42 76 Q60 91 78 76" fill="none" stroke="#08080a" stroke-width="7" stroke-linecap="round"/><text x="60" y="35" text-anchor="middle" font-size="24">${decodeURIComponent(label)}</text><path d="M20 88 Q60 112 100 88" fill="none" stroke="${c.color}" stroke-width="9" stroke-linecap="round"/></svg>`;}
  function stageForExp(exp){return exp>=900?2:exp>=350?1:0;}
  function persistCharState(){try{localStorage.setItem('nx_char_exp',JSON.stringify(charExp));localStorage.setItem('nx_owned_chars',JSON.stringify(Array.from(ocChars||[])));}catch(e){}if((typeof user!=='undefined'&&user)){try{sb.from('profiles').upsert({user_id:user.id,char_exp:charExp,updated_at:new Date().toISOString()},{onConflict:'user_id'}).then(()=>{}).catch(()=>{});}catch(e){}}}
  window.showCharSummon=function(charKey,pt,exp,mode){
    const ch=OFFICIAL_CHARS[charKey]||OFFICIAL_CHARS.ネクスケ, oldStage=stageForExp(Math.max(0,(charExp[charKey]||0)-exp)), newStage=stageForExp(charExp[charKey]||0), evo=newStage>oldStage;
    const el=document.getElementById('char-summon');if(!el){toast(charKey+' EXP+'+exp);return;}
    el.style.setProperty('--summon-color',ch.color);el.style.setProperty('--c',ch.color);
    if(!el.querySelector('.nx-summon-stage'))el.insertAdjacentHTML('afterbegin','<div class="nx-summon-stage"></div>');
    document.getElementById('summon-char').innerHTML=charSvg(charKey,106);
    document.getElementById('summon-name').textContent=(evo?'EVOLUTION · ':'')+ch.evo[newStage];
    document.getElementById('summon-catch').innerHTML=(evo?'<div class="nx-evo-title">CHARACTER EVOLUTION</div>':'')+safe(ch.line[newStage]||ch.line[0]);
    document.getElementById('summon-pts').textContent=(mode==='owned'?'EXP+':'+'+pt+'pt ＋ EXP+')+exp;
    document.getElementById('summon-close').textContent=evo?'進化した！':'仲間になった！';
    el.classList.add('on');
  };
  function installCharSystem(){
    if(typeof OC!=='undefined')Object.keys(OFFICIAL_CHARS).forEach(k=>{if(!OC[k])OC[k]={color:OFFICIAL_CHARS[k].color,genre:OFFICIAL_CHARS[k].genre,kuchi:OFFICIAL_CHARS[k].line[0],pers:'Nexca公式キャラクター。体験参加でEXPを集めて進化する。',weak:'まだ未知の体験が足りない。',compat:'ネクスケ',cd:'一緒に街を広げる相棒。',catch:OFFICIAL_CHARS[k].line[0],mbti:{E:60,N:70,F:65,P:70},strengths:['発見','参加','成長'],growth:'参加コードで体験を証明すると進化に近づく。',lvUp:[]};});
    if(typeof EVS!=='undefined')EVS.forEach(ev=>{const k=charForEvent(ev);ev.charKey=k;ev.charEmoji=OFFICIAL_CHARS[k].icon;ev.charName=ev.charName||OFFICIAL_CHARS[k].evo[stageForExp(charExp[k]||0)];ev.charDesc=OFFICIAL_CHARS[k].line[stageForExp(charExp[k]||0)];});
  }
  const oldSubmitPart=window.submitPart;
  window.submitPart=async function(){
    const code=document.getElementById('part-code')&&document.getElementById('part-code').value.trim().toUpperCase();
    const ev=EVS.find(e=>e.id===partEvId); if(!ev)return;
    if(!code||code.length<3){toast('参加コードを入力してください');return;}
    if(code!==String(ev.qr||'').toUpperCase()){document.getElementById('partm-content').innerHTML=`<div style="color:var(--red);font-weight:900;text-align:center;padding:18px;">コードが違います。主催者の画面に表示されている参加コードを確認してください。</div><button class="part-sub" onclick="openPartM('${ev.id}')">もう一度入力する</button>`;return;}
    const eid=publicId(ev.id), key='part_'+eid;
    if(parts[ev.id]||localStorage.getItem(key)==='1'){document.getElementById('partm-content').innerHTML='<div style="color:var(--green);font-weight:900;text-align:center;padding:20px;">この参加コードは使用済みです。キャラはもう仲間になっています。</div><button class="part-sub" onclick="closePartM()">閉じる</button>';return;}
    if((typeof user!=='undefined'&&user)){
      try{const chk=await sb.from('participations').select('id').eq('user_id',user.id).eq('event_id',eid).maybeSingle();if(chk.data){parts[ev.id]='ok';localStorage.setItem(key,'1');document.getElementById('partm-content').innerHTML='<div style="color:var(--green);font-weight:900;text-align:center;padding:20px;">この参加コードは使用済みです。</div><button class="part-sub" onclick="closePartM()">閉じる</button>';return;}}catch(e){}
    }
    parts[ev.id]='ok';localStorage.setItem(key,'1');
    const charKey=charForEvent(ev), owned=!!(charExp[charKey]&&charExp[charKey]>0), ptG=ev.fixed?80:120, expG=owned?90:140;
    if((typeof user!=='undefined'&&user)){try{await sb.from('participations').insert({user_id:user.id,event_id:eid,code:code,points:ptG,created_at:new Date().toISOString(),age_group:age,city:city,character:charKey});}catch(e){}}
    addPt('参加証明：'+ev.title,ptG,false,'part_'+eid);
    const before=charExp[charKey]||0; charExp[charKey]=before+expG; ocChars.add('CHAR_'+charKey); persistCharState();
    setTimeout(()=>{closePartM();showCharSummon(charKey,ptG,expG,owned?'owned':'new');renderOcGrid&&renderOcGrid();renderTownChars&&renderTownChars();},450);
  };
  function tuneEconomy(){
    if(typeof SHOP!=='undefined'){const costs={g1:120,g2:180,g3:280,g4:420,g5:900};SHOP.forEach(s=>{if(costs[s.id])s.cost=costs[s.id];});}
    if(typeof EARN!=='undefined'){EARN.forEach(e=>{if(e.name==='動画視聴')e.pt=5;if(e.name==='いいね')e.pt=8;if(e.name==='行きたい登録')e.pt=8;if(e.name==='診断完了')e.pt=60;if(e.name==='参加証明')e.pt=120;if(e.name==='振り返り投稿')e.pt=50;if(e.name==='ログイン')e.pt=10;});}
  }
  function enhanceGacha(){
    if(typeof GACHA==='undefined')return;
    GACHA.Common=[{text:'いまいる場所から徒歩10分以内で、入ったことのない店を1つ保存する',ev:'小さな新規探索は継続しやすい',type:'外',pts:40},{text:'気になったイベントを1つ「行きたい」に入れる',ev:'意思表示は行動率を上げる',type:'家',pts:35}];
    GACHA.Uncommon=[{text:'カフェか古着のスポットを1つ友達に送る',ev:'共有は参加のハードルを下げる',type:'家',pts:60},{text:'今日の広島で見つけた“いい違和感”を写真に残す',ev:'観察の習慣は街への愛着を高める',type:'外',pts:70}];
    GACHA.Rare=[{text:'Nexca掲載スポットを1つ開いて、地図まで確認する',ev:'移動イメージは実参加率を上げる',type:'外',pts:100}];
    GACHA.Epic=[{text:'半日で「カフェ→古着→川沿い」を1本の物語として回る',ev:'複数体験の連結は記憶に残りやすい',type:'外',pts:160}];
    GACHA.Legendary=[{text:'今日、Nexcaで見つけた体験を本当に1つやる。証明コードまで取りに行く',ev:'行動完了は自己効力感を大きく伸ばす',type:'外',pts:260}];
  }
  const prevOpenGacha=window.openGacha;
  window.openGacha=async function(){const cine=document.getElementById('nx-gacha-cinema');if(cine){cine.classList.add('on');setTimeout(()=>cine.classList.remove('on'),2300);}setTimeout(()=>prevOpenGacha(),900);};
  const oldSelQ=window.selQ;
  window.selQ=function(oi){try{if((typeof user!=='undefined'&&user)&&typeof dQ!=='undefined'&&dQ[cQ]){const q=dQ[cQ];sb.from('diagnosis_answers').insert({user_id:user.id,question_no:q.n||cQ+1,answer_index:oi,age_group:age,city:city,created_at:new Date().toISOString()}).then(()=>{}).catch(()=>{});}}catch(e){}oldSelQ(oi);};
  const oldRenderOc=window.renderOcGrid;
  window.renderOcGrid=function(){const el=document.getElementById('official-char-grid');if(!el)return oldRenderOc&&oldRenderOc();el.innerHTML=Object.keys(OFFICIAL_CHARS).map(k=>{const exp=charExp[k]||0, st=stageForExp(exp), got=exp>0||ocChars.has('CHAR_'+k);return `<div class="char-cell ${got?'got':''}" onclick="charExp['${k}']=(charExp['${k}']||0)+80;persistCharState&&persistCharState();showCharSummon('${k}',0,80,'owned');renderOcGrid();"><div class="nx-char-svg" style="--c:${OFFICIAL_CHARS[k].color};">${got?charSvg(k,42):'?'}</div><div class="char-cell-name ${got?'got':''}" style="${got?'color:'+OFFICIAL_CHARS[k].color:''}">${got?OFFICIAL_CHARS[k].evo[st]:'???'}</div><div style="font-size:7px;color:${OFFICIAL_CHARS[k].color};">EXP ${exp}</div></div>`;}).join('');};
  const oldTownChars=window.renderTownChars;
  window.renderTownChars=function(){const el=document.getElementById('town-chars-scroll');if(!el)return;el.innerHTML=Object.keys(OFFICIAL_CHARS).map(k=>{const exp=charExp[k]||0, active=(townData.chars||[]).some(c=>c.key===k);return `<div class="town-char-thumb ${active?'in-town':''}" onclick="toggleCharInTown('${k}')"><div class="nx-char-svg" style="--c:${OFFICIAL_CHARS[k].color};">${charSvg(k,38)}</div><div class="town-char-thumb-name" style="color:${OFFICIAL_CHARS[k].color};">${k}</div><div style="font-size:7px;color:${OFFICIAL_CHARS[k].color};">EXP ${exp}</div></div>`;}).join('');};
  window.renderTownMap=function(){const layer=document.getElementById('town-items-layer'),empty=document.getElementById('town-empty-msg');if(!layer)return;const hour=new Date().getHours(),night=hour>=19||hour<6;const sky=document.querySelector('.town-sky'),ground=document.querySelector('.town-ground');if(sky)sky.style.background=night?'linear-gradient(180deg,#02040f,#07133a)':'linear-gradient(180deg,#77c7ff,#f8d37c)';if(ground)ground.style.background='linear-gradient(180deg,#1d5f33,#083018)';const has=(townData.items||[]).length||(townData.chars||[]).length;if(empty)empty.style.display=has?'none':'flex';layer.innerHTML='<div class="nx-town-road"></div>';const defaults=[['🏪',18,70],['☕',36,62],['👗',58,68],['🎪',78,58],['⛩️',82,78]];defaults.forEach(b=>layer.insertAdjacentHTML('beforeend',`<div class="nx-town-building" style="left:${b[1]}%;top:${b[2]}%">${b[0]}</div>`));(townData.items||[]).forEach(item=>layer.insertAdjacentHTML('beforeend',`<div class="town-el" style="left:${item.x}%;top:${item.y}%">${safe(item.em)}</div>`));(townData.chars||[]).forEach((tc,i)=>{const k=tc.key,ch=OFFICIAL_CHARS[k]||OFFICIAL_CHARS.ネクスケ,x=tc.x||20+i*12,y=tc.y||55+(i%3)*9;layer.insertAdjacentHTML('beforeend',`<div class="town-char-el" style="left:${x}%;top:${y}%;--c:${ch.color};animation-delay:${i*.3}s" onclick="openTcm('${k}')"><div class="nx-town-chat">${safe(ch.line[stageForExp(charExp[k]||0)])}</div><div class="nx-char-svg" style="--c:${ch.color};">${charSvg(k,42)}</div></div>`);});updateTownLevel&&updateTownLevel();};
  window.updateTownLevel=function(){const n=(townData.items||[]).length+(townData.chars||[]).length,lv=Math.max(1,Math.floor(n/2)+1),pct=Math.min(100,(n%2)*50+20);const b=document.getElementById('town-lv-badge'),name=document.getElementById('town-lv-name'),sub=document.getElementById('town-lv-sub'),fill=document.getElementById('town-lv-fill');if(b)b.textContent='LV'+lv;if(name)name.textContent=lv>=5?'にぎわうNexcaタウン':lv>=3?'育ちはじめた街':'新しい街';if(sub)sub.textContent='キャラと建物を増やすほど街がにぎわう';if(fill)fill.style.width=pct+'%';};
  window.persistCharState=persistCharState;
  function bootGameLayer(){installNexcaGameLayer();tuneEconomy();enhanceGacha();installCharSystem();renderOcGrid&&renderOcGrid();renderTownChars&&renderTownChars();}
  window.addEventListener('DOMContentLoaded',()=>{bootGameLayer();setTimeout(()=>{bootGameLayer();renderFeed&&renderFeed();renderShop&&renderShop();renderEarn&&renderEarn();},900);});
  window.addEventListener('DOMContentLoaded',()=>{extendData();overrideCore();hydrateGroupGacha();renderGenreOpts&&renderGenreOpts();renderFlyerTabs&&renderFlyerTabs();renderFeed&&renderFeed();applyProfile();const ob=$('#ob');if(ob&&(localStorage.getItem('nx_onboarding_done')==='1'||localStorage.getItem('nx_prereg')==='1')&&localStorage.getItem('nx_age'))ob.classList.add('hide');});
})();


