(function(){
  'use strict';
  const D=window.NexcaData, $=s=>document.querySelector(s), esc=D.esc;
  const draft={step:1,tags:[],production_support_types:[]};
  function data(){return D.load();}
  function myOrg(){return data().organizers.find(o=>o.id==='org-local')||data().organizers[0];}
  function myApps(){const org=myOrg();return data().listing_applications.filter(a=>a.organizer_id===org.id);}
  function contracts(){const org=myOrg();return data().organizer_contracts.filter(c=>c.organizer_id===org.id);}
  function boot(){document.body.innerHTML=shell();renderAll();}
  function shell(){return `<div class="nxp"><div class="nxp-head"><div class="nxp-head-in"><div class="nxp-logo">NEX<span>CA</span></div><div class="nxp-badge">ORGANIZER</div><div class="nxp-spacer"></div><button class="nxp-btn ghost" onclick="location.href='index.html'">ユーザー画面へ</button><button class="nxp-btn ghost">ログアウト</button></div></div><div class="nxp-shell"><div class="nxp-tabs">${['home:ダッシュボード','contract:契約同意','apply:掲載申請','apps:申請一覧','analytics:簡易分析','plan:料金'].map((x,i)=>{const [id,l]=x.split(':');return `<button class="nxp-tab ${i?'':'on'}" onclick="OrganizerP1.tab('${id}',this)">${l}</button>`}).join('')}</div>${['home','contract','apply','apps','analytics','plan'].map((id,i)=>`<section id="${id}" class="nxp-screen ${i?'':'on'}"></section>`).join('')}</div></div>`;}
  function tab(id,btn){document.querySelectorAll('.nxp-tab').forEach(b=>b.classList.remove('on'));btn.classList.add('on');document.querySelectorAll('.nxp-screen').forEach(s=>s.classList.remove('on'));$('#'+id).classList.add('on');if(id==='apply')renderApply();}
  function go(id){tab(id,document.querySelector(`[onclick*="'${id}'"]`));}
  function renderAll(){renderHome();renderContract();renderApply();renderApps();renderAnalytics();renderPlan();}
  function renderHome(){const org=myOrg(), apps=myApps(), cs=contracts(), published=apps.filter(a=>a.status==='published').length, listings=data().listings.filter(l=>l.organizer_id===org.id), likes=data().likes.filter(x=>listings.some(l=>l.id===x.listing_id)).length, wants=data().wanted_listings.filter(x=>listings.some(l=>l.id===x.listing_id)).length, clicks=data().link_clicks.filter(x=>listings.some(l=>l.id===x.listing_id)).length, codes=data().participation_code_redemptions.filter(x=>listings.some(l=>l.id===x.listing_id)).length;$('#home').innerHTML=`<div class="nxp-hero"><div class="nxp-card"><div class="nxp-title">掲載申請から公開まで、Web上で完結</div><div class="nxp-sub">申請はNexca運営に届き、確認・差し戻し・承認後にユーザー画面へ掲載されます。</div><div class="nxp-actions"><button class="nxp-btn" onclick="OrganizerP1.go('apply')">新規掲載を作成</button><button class="nxp-btn ghost" onclick="OrganizerP1.go('contract')">契約同意</button></div></div><div class="nxp-card"><div class="nxp-title">${esc(org.name||'主催者情報未登録')}</div><div class="nxp-sub">${esc(org.area||'広島市中区')} / ${esc((org.genres||[]).join('・'))}</div><div class="nxp-pills"><span class="nxp-pill ${cs.length?'green':'red'}">${cs.length?'同意済み':'契約未同意'}</span><span class="nxp-pill yellow">初期掲載パートナー対象</span></div></div></div><div class="nxp-kpis">${[['申請数',apps.length],['公開中',published],['いいね合計',likes],['行きたい合計',wants],['リンククリック',clicks],['参加コード使用',codes],['契約同意',cs.length?'済':'未'],['次にやること',apps.length?'審査状況確認':'最初の掲載作成']].map(x=>`<div class="nxp-kpi"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div><div class="nxp-card"><div class="nxp-title" style="font-size:16px">主催者登録</div>${profileForm(org)}</div>${apps.length?'':`<div class="nxp-card"><div class="nxp-title" style="font-size:16px">まだ掲載申請がありません</div><p class="nxp-sub">最初の掲載を作成すると、ここに審査状況と反応データが表示されます。</p><button class="nxp-btn" onclick="OrganizerP1.go('apply')">新規掲載を作成</button></div>`}`;}
  function profileForm(p){return `<div class="nxp-form"><div class="nxp-split"><div><label>主催者名/店舗名</label><input class="nxp-input" id="org-name" value="${esc(p.name||'')}"></div><div><label>担当者名</label><input class="nxp-input" id="org-person" value="${esc(p.contact_name||'')}"></div></div><div class="nxp-split"><div><label>メール</label><input class="nxp-input" id="org-email" value="${esc(p.email||'')}"></div><div><label>電話番号</label><input class="nxp-input" id="org-phone" value="${esc(p.phone_number||'')}"></div></div><div class="nxp-split"><div><label>Instagram</label><input class="nxp-input" id="org-ig" value="${esc(p.instagram_url||'')}"></div><div><label>HP</label><input class="nxp-input" id="org-web" value="${esc(p.website_url||'')}"></div></div><label>説明文</label><textarea class="nxp-textarea" id="org-desc">${esc(p.description||'')}</textarea><div class="nxp-split"><div><label>活動地域</label><input class="nxp-input" id="org-area" value="${esc(p.area||'広島市中区')}"></div><div><label>ジャンル</label><select class="nxp-select" id="org-genre">${D.categories.map(g=>`<option ${p.genres?.includes(g)?'selected':''}>${g}</option>`).join('')}</select></div></div><button class="nxp-btn" onclick="OrganizerP1.saveProfile()">主催者情報を保存</button></div>`;}
  function saveProfile(){D.saveOrganizerProfile({id:'org-local',owner_user_id:'local-organizer',name:$('#org-name').value,contact_name:$('#org-person').value,email:$('#org-email').value,phone_number:$('#org-phone').value,instagram_url:$('#org-ig').value,website_url:$('#org-web').value,description:$('#org-desc').value,area:$('#org-area').value,genres:[$('#org-genre').value],show_phone:false,is_initial_partner:true,discount_rate:30});alert('保存しました');renderAll();}
  function renderContract(){const org=myOrg(), c=contracts();$('#contract').innerHTML=`<div class="nxp-card"><div class="nxp-title">Nexca掲載同意書</div><p class="nxp-sub">契約書バージョン: nexca_listing_terms_v1。正式文言は後から差し替え可能です。</p><div class="nxp-row"><h3>Nexca掲載に関する同意</h3><p>主催者は、提出する掲載情報・素材の利用権限を持ち、内容が正確であることを確認します。Nexcaは掲載前に内容確認を行い、必要に応じて差し戻しできます。</p></div><div class="nxp-form">${['契約内容を確認しました','掲載素材の利用を許可します','掲載情報の正確性を確認しました','SNS紹介を許可します','掲載後アンケートに協力します'].map((x,i)=>`<label class="nxp-check"><input type="checkbox" id="ct-${i}"><span>${x}</span></label>`).join('')}<div class="nxp-split"><div><label>署名者名</label><input class="nxp-input" id="ct-signer" value="${esc(org.contact_name||'')}"></div><div><label>店舗/会社名</label><input class="nxp-input" id="ct-store" value="${esc(org.name||'')}"></div></div><button class="nxp-btn green" onclick="OrganizerP1.signContract()">同意して保存</button></div></div><div class="nxp-card"><div class="nxp-title" style="font-size:16px">同意履歴</div>${c.length?c.map(x=>`<div class="nxp-row"><h3>同意済み</h3><p>${esc(x.company_or_store_name)} / ${esc(x.signer_name)} / ${esc(x.signed_at)}</p></div>`).join(''):'<p class="nxp-muted">契約同意履歴はまだありません。</p>'}</div>`;}
  function signContract(){if(![0,1,2,3,4].every(i=>$('#ct-'+i).checked)){alert('すべての確認項目にチェックしてください');return;}D.signContract({organizer_id:myOrg().id,signer_name:$('#ct-signer').value,company_or_store_name:$('#ct-store').value});alert('同意履歴を保存しました');renderAll();}
  function renderApply(){const s=draft.step;$('#apply').innerHTML=`<div class="nxp-card"><div class="nxp-title">掲載申請フォーム</div><p class="nxp-sub">Step ${s}/6。主催者は住所だけ入力してください。緯度経度は運営が補正します。</p><div class="nxp-steps">${[1,2,3,4,5,6].map(n=>`<span class="${n===s?'on':''}">${n}</span>`).join('')}</div>${stepHtml(s)}<div class="nxp-actions"><button class="nxp-btn ghost" onclick="OrganizerP1.prevStep()">戻る</button><button class="nxp-btn" onclick="OrganizerP1.nextStep()">${s===6?'申請内容を確認して送信':'次へ'}</button></div></div>`;}
  function field(id,label,type='input'){return `<label>${label}</label><${type==='textarea'?'textarea':'input'} class="${type==='textarea'?'nxp-textarea':'nxp-input'}" id="${id}">${type==='textarea'?(draft[id]||''):''}${type==='textarea'?'</textarea>':''}`;}
  function stepHtml(s){
    if(s===1)return `<div class="nxp-grid">${[['flyer','チラシ掲載','まとめ見と詳細ページに掲載。動画なしでも始められる軽量プラン。'],['video','動画掲載','動画フィード、まとめ見、詳細ページに掲載。Nexcaの標準プラン。'],['video_with_thumbnail','動画＋サムネ掲載','動画フィードに加え、まとめ見でもサムネイルで見せられるプラン。']].map(x=>`<button class="nxp-card nxp-choice ${draft.media_type===x[0]?'on':''}" onclick="OrganizerP1.pick('media_type','${x[0]}')"><div class="nxp-title" style="font-size:16px">${x[1]}</div><p class="nxp-sub">${x[2]}</p></button>`).join('')}</div>`;
    if(s===2)return `<div class="nxp-form"><label>掲載タイトル</label><input class="nxp-input" id="title" value="${esc(draft.title||'')}"><label>一言キャッチコピー</label><input class="nxp-input" id="catchcopy" value="${esc(draft.catchcopy||'')}"><label>ジャンル</label><select class="nxp-select" id="category">${D.categories.map(g=>`<option ${draft.category===g?'selected':''}>${g}</option>`).join('')}</select>${field('description','説明文','textarea')}${field('detail_info','詳細情報','textarea')}${field('unique_info','ユニーク情報','textarea')}${field('notes','注意事項','textarea')}</div>`;
    if(s===3)return `<div class="nxp-form"><label>日程タイプ</label><select class="nxp-select" id="event_date_type"><option value="fixed_date">単日開催</option><option value="date_range">期間開催</option><option value="evergreen">通年/常設</option></select><div class="nxp-split"><div><label>開始日</label><input class="nxp-input" type="date" id="start_date" value="${esc(draft.start_date||'')}"></div><div><label>終了日</label><input class="nxp-input" type="date" id="end_date" value="${esc(draft.end_date||'')}"></div></div><label>営業時間</label><input class="nxp-input" id="business_hours" value="${esc(draft.business_hours||'')}"><label>住所</label><input class="nxp-input" id="address" value="${esc(draft.address||'')}"><label>料金</label><input class="nxp-input" id="price_text" placeholder="例：無料 / ¥500〜¥1,000" value="${esc(draft.price_text||'')}"><label>対象年齢</label><input class="nxp-input" id="target_age_groups" value="${esc(draft.target_age_groups||'中学生,高校生,大学生,社会人')}"></div>`;
    if(s===4)return `<div class="nxp-form"><label>動画・素材準備状況</label><select class="nxp-select" id="material_status">${['掲載用の動画を持っている','チラシ/画像のみ持っている','Instagram/TikTokなど既存投稿URLを使いたい','Nexcaに動画編集を依頼したい','Nexcaに撮影から依頼したい','どれが良いか相談したい'].map(x=>`<option>${x}</option>`).join('')}</select><label>制作サポート希望</label><div class="nxp-grid">${['希望しない','動画編集だけ相談したい','撮影から相談したい','投稿文/キャッチコピー作成を相談したい','料金を見てから決めたい'].map(x=>`<label class="nxp-check"><input type="checkbox" name="support" value="${x}"><span>${x}</span></label>`).join('')}</div><div class="nxp-split"><div><label>Instagram URL</label><input class="nxp-input" id="instagram_url" value="${esc(draft.instagram_url||'')}"></div><div><label>HP URL</label><input class="nxp-input" id="website_url" value="${esc(draft.website_url||'')}"></div></div><label>外部予約/申込リンク</label><input class="nxp-input" id="reservation_url" value="${esc(draft.reservation_url||'')}"><label>メディアURL</label><input class="nxp-input" id="media_url" value="${esc(draft.media_url||'')}"><label>サムネイルURL</label><input class="nxp-input" id="thumbnail_url" value="${esc(draft.thumbnail_url||'')}"><label>制作希望メモ</label><textarea class="nxp-textarea" id="production_memo">${esc(draft.production_memo||'')}</textarea></div>`;
    if(s===5)return `<div class="nxp-form"><p class="nxp-sub">タグは最大3つまで選択できます。運営が最終確認します。</p><div id="selected-tags" class="nxp-pills">${(draft.tags||[]).map(t=>`<span class="nxp-pill green">${esc(t)}</span>`).join('')}</div>${Object.entries(D.tagGroups).map(([g,ts])=>`<div class="nxp-row"><h3>${g}</h3><div class="nxp-pills">${ts.map(t=>`<button class="nxp-tag ${draft.tags?.includes(t)?'on':''}" onclick="OrganizerP1.toggleTag('${t}')">${t}</button>`).join('')}</div></div>`).join('')}<label class="nxp-check"><input type="checkbox" id="participation_code_requested" ${draft.participation_code_requested?'checked':''}><span>参加コード発行を希望する</span></label><label class="nxp-check"><input type="checkbox" id="accepts_nexca_interest" checked><span>Nexca内参加希望を受け付ける</span></label></div>`;
    return `<div class="nxp-row"><h3>${esc(draft.title||'無題')}</h3><p>${esc(draft.catchcopy||'')}<br>${esc(draft.category||'未選択')} / ${esc(draft.media_type||'未選択')} / ${esc(draft.price_text||'料金未入力')}</p><div class="nxp-pills">${(draft.tags||[]).map(t=>`<span class="nxp-pill">${esc(t)}</span>`).join('')}</div></div><p class="nxp-sub">送信すると status=submitted として保存され、運営画面の申請一覧に表示されます。</p>`;
  }
  function readStep(){['title','catchcopy','category','description','detail_info','unique_info','notes','event_date_type','start_date','end_date','business_hours','address','price_text','target_age_groups','material_status','instagram_url','website_url','reservation_url','media_url','thumbnail_url','production_memo'].forEach(id=>{const el=$('#'+id);if(el)draft[id]=el.value;});draft.production_support_types=[...document.querySelectorAll('input[name="support"]:checked')].map(x=>x.value);const pc=$('#participation_code_requested');if(pc)draft.participation_code_requested=pc.checked;const ni=$('#accepts_nexca_interest');if(ni)draft.accepts_nexca_interest=ni.checked;}
  function nextStep(){readStep();if(draft.step<6){draft.step++;renderApply();return;}const org=myOrg();D.submitApplication({...draft,organizer_id:org.id,production_support_requested:(draft.production_support_types||[]).some(x=>x!=='希望しない'),production_status:(draft.production_support_types||[]).length?'consultation_requested':'not_needed',target_age_groups:String(draft.target_age_groups||'').split(',').map(x=>x.trim()).filter(Boolean)});alert('申請を送信しました。現在、Nexca運営が内容を確認しています。');draft.step=1;Object.keys(draft).forEach(k=>{if(k!=='step')delete draft[k];});renderAll();go('apps');}
  function prevStep(){readStep();draft.step=Math.max(1,draft.step-1);renderApply();}
  function pick(k,v){draft[k]=v;renderApply();}
  function toggleTag(t){draft.tags=draft.tags||[];if(draft.tags.includes(t))draft.tags=draft.tags.filter(x=>x!==t);else if(draft.tags.length<3)draft.tags.push(t);else alert('タグは最大3つまでです');renderApply();}
  function renderApps(){const apps=myApps();$('#apps').innerHTML=`<div class="nxp-card"><div class="nxp-title">申請一覧</div><p class="nxp-sub">掲載申請を作成すると、ここに審査状況が表示されます。</p></div><div class="nxp-list">${apps.length?apps.map(appCard).join(''):`<div class="nxp-card"><div class="nxp-title" style="font-size:16px">申請はまだありません</div><p class="nxp-sub">掲載申請を作成すると、ここに審査状況が表示されます。</p><button class="nxp-btn" onclick="OrganizerP1.go('apply')">新規掲載を作成</button></div>`}</div>`;}
  function appCard(a){const l=D.listingById(a.listing_id)||{};return `<div class="nxp-row"><div class="nxp-row-top"><div class="nxp-icon">${l.category==='古着'?'👕':l.category==='カフェ'?'☕':'🎪'}</div><div><h3>${esc(l.title||'無題')}</h3><p>${esc(l.catchcopy||'')}<br>${esc(l.category||'')} / ${labelStatus(a.status)} / ${esc(a.submitted_at?.slice(0,10)||'')}</p><div class="nxp-pills"><span class="nxp-pill ${a.status==='published'?'green':a.status==='revision_requested'?'red':'yellow'}">${labelStatus(a.status)}</span><span class="nxp-pill">${a.production_support_requested?'制作相談あり':'制作不要'}</span></div>${a.admin_comment?`<p class="nxp-muted">運営コメント: ${esc(a.admin_comment)}</p>`:''}</div></div><div class="nxp-actions"><button class="nxp-btn ghost" onclick="OrganizerP1.resubmit('${a.id}')">再提出</button></div></div>`;}
  function labelStatus(s){return {draft:'下書き',submitted:'申請中',reviewing:'確認中',revision_requested:'差し戻し',organizer_confirmation:'主催者確認待ち',approved:'承認済み',scheduled:'公開予約',published:'公開中',archived:'掲載終了',hidden:'非公開',rejected:'却下'}[s]||s;}
  function resubmit(id){D.updateApplication(id,{status:'submitted',organizer_reply:'修正して再提出しました'});renderAll();}
  function renderAnalytics(){const org=myOrg(), listings=data().listings.filter(l=>l.organizer_id===org.id), d=data(), likes=d.likes.filter(x=>listings.some(l=>l.id===x.listing_id)).length, wants=d.wanted_listings.filter(x=>listings.some(l=>l.id===x.listing_id)).length, clicks=d.link_clicks.filter(x=>listings.some(l=>l.id===x.listing_id)).length, interest=d.link_clicks.filter(x=>listings.some(l=>l.id===x.listing_id)&&x.link_type==='nexca_interest').length, codes=d.participation_code_redemptions.filter(x=>listings.some(l=>l.id===x.listing_id)).length;$('#analytics').innerHTML=`<div class="nxp-kpis">${[['いいね数',likes],['行きたい数',wants],['リンククリック',clicks],['Nexca参加希望',interest],['参加コード使用',codes]].map(x=>`<div class="nxp-kpi"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div><div class="nxp-card"><div class="nxp-title" style="font-size:16px">投稿別パフォーマンス</div>${listings.length?listings.map(l=>`<div class="nxp-row"><h3>${esc(l.title)}</h3><p>いいね ${l.like_count||0} / 行きたい ${l.want_count||0} / シェア ${l.share_count||0} / クリック ${l.link_click_count||0}</p></div>`).join(''):'<p class="nxp-muted">掲載後、ここにユーザーの反応が表示されます。</p>'}</div><div class="nxp-card"><div class="nxp-title" style="font-size:16px">有料分析予定</div><p class="nxp-muted">年齢層別反応、地域別反応、タグ別反応、日別クリックを追加できます。</p><div class="nxp-chart"><span></span><span></span><span></span><span></span><span></span></div></div>`;}
  function renderPlan(){const plans=data().pricing_plans;$('#plan').innerHTML=`<div class="nxp-card"><div class="nxp-title">料金について</div><p class="nxp-sub">2026年12月31日まで初期掲載無料。先着100社は2027年1月以降の掲載費30%OFFを永久適用します。</p></div><div class="nxp-grid">${plans.map(p=>`<div class="nxp-card"><div class="nxp-title" style="font-size:17px">${esc(p.name)}</div><p class="nxp-sub">${esc(p.description)}</p><div class="nxp-pills"><span class="nxp-pill green">${p.is_free_until_2026_end?'無料期間対象':'オプション'}</span><span class="nxp-pill yellow">${p.is_initial_partner_discount_target?'100社30%OFF対象':'個別相談'}</span></div></div>`).join('')}</div>`;}
  window.OrganizerP1={tab,go,saveProfile,signContract,nextStep,prevStep,pick,toggleTag,resubmit};
  document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,80));
})();
