-- Nexca v2 support schema
-- Run this in Supabase SQL Editor after reviewing existing policies.

alter table public.profiles
  add column if not exists age_group text,
  add column if not exists city text,
  add column if not exists town_data jsonb not null default '{}'::jsonb,
  add column if not exists char_exp jsonb not null default '{}'::jsonb,
  add column if not exists total_points integer not null default 0;

alter table public.events
  add column if not exists char_image_url text,
  add column if not exists char_name text,
  add column if not exists char_desc text,
  add column if not exists website_url text,
  add column if not exists booking_url text,
  add column if not exists participation_code text,
  add column if not exists is_active boolean not null default true;

alter table public.participations
  add column if not exists code text,
  add column if not exists points integer not null default 0,
  add column if not exists age_group text,
  add column if not exists city text,
  add column if not exists character text,
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists participations_user_event_once
  on public.participations(user_id, event_id);

alter table public.likes
  add column if not exists created_at timestamptz not null default now();

alter table public.event_link_clicks
  add column if not exists link_type text,
  add column if not exists click_type text,
  add column if not exists user_id uuid,
  add column if not exists clicked_at timestamptz not null default now();

create table if not exists public.diagnosis_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  question_no integer not null,
  answer_index integer not null,
  age_group text,
  city text,
  created_at timestamptz not null default now()
);

create table if not exists public.event_views (
  id bigint generated by default as identity primary key,
  event_id text not null,
  user_id uuid,
  age_group text,
  city text,
  viewed_at timestamptz not null default now()
);

create index if not exists likes_event_created_idx on public.likes(event_id, created_at);
create index if not exists event_clicks_event_clicked_idx on public.event_link_clicks(event_id, clicked_at);
create index if not exists views_event_viewed_idx on public.event_views(event_id, viewed_at);
create index if not exists diagnosis_user_created_idx on public.diagnosis_answers(user_id, created_at);

alter table public.diagnosis_answers enable row level security;
alter table public.event_views enable row level security;

drop policy if exists "users insert own diagnosis answers" on public.diagnosis_answers;
create policy "users insert own diagnosis answers"
  on public.diagnosis_answers for insert
  with check (auth.uid() = user_id);

drop policy if exists "users read own diagnosis answers" on public.diagnosis_answers;
create policy "users read own diagnosis answers"
  on public.diagnosis_answers for select
  using (auth.uid() = user_id);

drop policy if exists "users insert own event views" on public.event_views;
create policy "users insert own event views"
  on public.event_views for insert
  with check (user_id is null or auth.uid() = user_id);

drop policy if exists "organizers read event views" on public.event_views;
create policy "organizers read event views"
  on public.event_views for select
  using (
    exists (
      select 1 from public.events e
      where e.id::text = event_views.event_id::text
      and e.organizer_id = auth.uid()
    )
  );
