-- Nexca v2 support schema
-- Run this in Supabase SQL Editor after reviewing existing policies.

alter table public.profiles
  add column if not exists age_group text,
  add column if not exists city text,
  add column if not exists role text,
  add column if not exists is_admin boolean not null default false,
  add column if not exists town_data jsonb not null default '{}'::jsonb,
  add column if not exists char_exp jsonb not null default '{}'::jsonb,
  add column if not exists last_lat double precision,
  add column if not exists last_lng double precision,
  add column if not exists total_points integer not null default 0;

alter table public.events
  add column if not exists char_image_url text,
  add column if not exists char_name text,
  add column if not exists char_desc text,
  add column if not exists status text not null default 'pending_review',
  add column if not exists submitted_by_role text not null default 'organizer',
  add column if not exists submitted_at timestamptz not null default now(),
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid,
  add column if not exists review_note text,
  add column if not exists rejection_reason text,
  add column if not exists data_plan text not null default 'free',
  add column if not exists thumbnail_url text,
  add column if not exists gacha_enabled boolean not null default true,
  add column if not exists gacha_conditions text,
  add column if not exists production_option text not null default 'self',
  add column if not exists lat double precision,
  add column if not exists lng double precision,
  add column if not exists mood_tags text[] not null default '{}'::text[],
  add column if not exists time_tags text[] not null default '{}'::text[],
  add column if not exists area_tags text[] not null default '{}'::text[],
  add column if not exists budget_max integer,
  add column if not exists indoor boolean not null default false,
  add column if not exists outdoor boolean not null default true,
  add column if not exists safety_level integer not null default 4,
  add column if not exists website_url text,
  add column if not exists booking_url text,
  add column if not exists participation_code text,
  add column if not exists is_active boolean not null default true;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'events_status_check'
      and conrelid = 'public.events'::regclass
  ) then
    alter table public.events
      add constraint events_status_check
      check (status in ('draft','pending_review','published','rejected','archived'))
      not valid;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'events_data_plan_check'
      and conrelid = 'public.events'::regclass
  ) then
    alter table public.events
      add constraint events_data_plan_check
      check (data_plan in ('free','paid'))
      not valid;
  end if;
end $$;

update public.events
set status = 'published'
where status = 'pending_review'
  and is_active = true
  and coalesce(show_in_feed, true) = true;

alter table public.participations
  add column if not exists code text,
  add column if not exists points integer not null default 0,
  add column if not exists age_group text,
  add column if not exists city text,
  add column if not exists character text,
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists participations_user_event_once
  on public.participations(user_id, event_id);

alter table public.likes
  add column if not exists created_at timestamptz not null default now();

alter table public.event_link_clicks
  add column if not exists link_type text,
  add column if not exists click_type text,
  add column if not exists user_id uuid,
  add column if not exists clicked_at timestamptz not null default now();

create table if not exists public.diagnosis_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  question_no integer not null,
  answer_index integer not null,
  age_group text,
  city text,
  created_at timestamptz not null default now()
);

create table if not exists public.event_views (
  id bigint generated by default as identity primary key,
  event_id text not null,
  user_id uuid,
  age_group text,
  city text,
  viewed_at timestamptz not null default now()
);

create table if not exists public.contract_acceptances (
  id bigint generated by default as identity primary key,
  event_id text not null,
  user_id uuid not null,
  contract_version text not null,
  accepted_at timestamptz not null default now(),
  user_agent text,
  terms_snapshot text,
  created_at timestamptz not null default now()
);

create index if not exists likes_event_created_idx on public.likes(event_id, created_at);
create index if not exists event_clicks_event_clicked_idx on public.event_link_clicks(event_id, clicked_at);
create index if not exists views_event_viewed_idx on public.event_views(event_id, viewed_at);
create index if not exists diagnosis_user_created_idx on public.diagnosis_answers(user_id, created_at);
create index if not exists events_status_submitted_idx on public.events(status, submitted_at);
create index if not exists events_organizer_status_idx on public.events(organizer_id, status);
create index if not exists contract_event_user_idx on public.contract_acceptances(event_id, user_id, accepted_at);

alter table public.diagnosis_answers enable row level security;
alter table public.event_views enable row level security;
alter table public.contract_acceptances enable row level security;

drop policy if exists "users insert own diagnosis answers" on public.diagnosis_answers;
create policy "users insert own diagnosis answers"
  on public.diagnosis_answers for insert
  with check (auth.uid() = user_id);

drop policy if exists "users read own diagnosis answers" on public.diagnosis_answers;
create policy "users read own diagnosis answers"
  on public.diagnosis_answers for select
  using (auth.uid() = user_id);

drop policy if exists "owner reads all diagnosis answers" on public.diagnosis_answers;
create policy "owner reads all diagnosis answers"
  on public.diagnosis_answers for select
  using ((auth.jwt() ->> 'email') = 'taichi102433@gmail.com');

drop policy if exists "users insert own event views" on public.event_views;
create policy "users insert own event views"
  on public.event_views for insert
  with check (user_id is null or auth.uid() = user_id);

drop policy if exists "organizers read event views" on public.event_views;
create policy "organizers read event views"
  on public.event_views for select
  using (
    exists (
      select 1 from public.events e
      where e.id::text = event_views.event_id::text
      and e.organizer_id = auth.uid()
    )
  );

drop policy if exists "users insert own contract acceptances" on public.contract_acceptances;
create policy "users insert own contract acceptances"
  on public.contract_acceptances for insert
  with check (auth.uid() = user_id);

drop policy if exists "users read own contract acceptances" on public.contract_acceptances;
create policy "users read own contract acceptances"
  on public.contract_acceptances for select
  using (auth.uid() = user_id);

drop policy if exists "admins read contract acceptances" on public.contract_acceptances;
create policy "admins read contract acceptances"
  on public.contract_acceptances for select
  using (
    (auth.jwt() ->> 'email') = 'taichi102433@gmail.com'
  );

-- Nexca Town game persistence
create table if not exists public.user_game_profiles (
  user_id uuid primary key,
  player_level integer not null default 1,
  player_exp integer not null default 0,
  points integer not null default 0,
  gems integer not null default 0,
  town_popularity integer not null default 0,
  town_rank integer not null default 1,
  login_streak integer not null default 0,
  last_login_date date,
  total_mini_games_played integer not null default 0,
  total_experience_cards integer not null default 0,
  total_participation_codes_redeemed integer not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.user_buildings (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  building_id text not null,
  genre text,
  level integer not null default 1,
  exp integer not null default 0,
  visual_stage integer not null default 1,
  reward_ready boolean not null default false,
  last_reward_collected_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, building_id)
);

create table if not exists public.user_characters (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  character_id text not null,
  name text not null,
  type text,
  rarity text,
  level integer not null default 1,
  exp integer not null default 0,
  skill_name text,
  skill_description text,
  dialogue text,
  costume text,
  is_main boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(user_id, character_id)
);

create table if not exists public.participation_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  description text,
  genre text,
  linked_place_id text,
  linked_event_id text,
  reward_points integer not null default 100,
  reward_player_exp integer not null default 80,
  reward_building_exp integer not null default 90,
  reward_character_exp integer not null default 70,
  reward_town_popularity integer not null default 25,
  reward_badge_id text,
  valid_from timestamptz,
  valid_until timestamptz,
  max_uses integer,
  used_count integer not null default 0,
  max_uses_per_user integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.participation_code_redemptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  code text not null,
  participation_code_id bigint references public.participation_codes(id) on delete set null,
  genre text,
  points_awarded integer not null default 0,
  player_exp_awarded integer not null default 0,
  building_exp_awarded integer not null default 0,
  character_exp_awarded integer not null default 0,
  redeemed_at timestamptz not null default now(),
  unique(user_id, code)
);

create table if not exists public.experience_cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  genre text,
  title text not null,
  place_name text,
  event_name text,
  visited_at date,
  points_earned integer not null default 0,
  exp_earned integer not null default 0,
  badge_id text,
  user_memo text,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_quests (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  quest_id text not null,
  title text not null,
  description text,
  target_action text,
  target_genre text,
  target_count integer not null default 1,
  current_count integer not null default 0,
  reward_points integer not null default 0,
  reward_exp integer not null default 0,
  is_completed boolean not null default false,
  is_claimed boolean not null default false,
  date date not null default current_date,
  unique(user_id, quest_id, date)
);

create table if not exists public.user_collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  item_id text not null,
  category text,
  genre text,
  rarity text,
  obtained_at timestamptz not null default now(),
  source_type text,
  unique(user_id, item_id)
);

create table if not exists public.mini_game_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  game_type text not null,
  score integer not null default 0,
  rank text,
  points_earned integer not null default 0,
  exp_earned integer not null default 0,
  played_at timestamptz not null default now()
);

create index if not exists game_profiles_rank_idx on public.user_game_profiles(town_rank, town_popularity desc);
create index if not exists buildings_user_idx on public.user_buildings(user_id);
create index if not exists characters_user_idx on public.user_characters(user_id);
create index if not exists participation_codes_active_idx on public.participation_codes(is_active, valid_from, valid_until);
create index if not exists redemptions_user_idx on public.participation_code_redemptions(user_id, redeemed_at);
create index if not exists cards_user_idx on public.experience_cards(user_id, created_at);
create index if not exists quests_user_date_idx on public.daily_quests(user_id, date);
create index if not exists collections_user_idx on public.user_collections(user_id, category);
create index if not exists mini_games_user_idx on public.mini_game_results(user_id, played_at);

alter table public.user_game_profiles enable row level security;
alter table public.user_buildings enable row level security;
alter table public.user_characters enable row level security;
alter table public.participation_codes enable row level security;
alter table public.participation_code_redemptions enable row level security;
alter table public.experience_cards enable row level security;
alter table public.daily_quests enable row level security;
alter table public.user_collections enable row level security;
alter table public.mini_game_results enable row level security;

drop policy if exists "users manage own game profile" on public.user_game_profiles;
create policy "users manage own game profile" on public.user_game_profiles
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own buildings" on public.user_buildings;
create policy "users manage own buildings" on public.user_buildings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own characters" on public.user_characters;
create policy "users manage own characters" on public.user_characters
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "active participation codes are readable" on public.participation_codes;
create policy "active participation codes are readable" on public.participation_codes
  for select using (is_active = true);

drop policy if exists "admins manage participation codes" on public.participation_codes;
create policy "admins manage participation codes" on public.participation_codes
  for all using ((auth.jwt() ->> 'email') = 'taichi102433@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'taichi102433@gmail.com');

drop policy if exists "users manage own redemptions" on public.participation_code_redemptions;
create policy "users manage own redemptions" on public.participation_code_redemptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own experience cards" on public.experience_cards;
create policy "users manage own experience cards" on public.experience_cards
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own daily quests" on public.daily_quests;
create policy "users manage own daily quests" on public.daily_quests
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own collections" on public.user_collections;
create policy "users manage own collections" on public.user_collections
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own mini game results" on public.mini_game_results;
create policy "users manage own mini game results" on public.mini_game_results
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
